def reverse(a):
    if a == {'T': 'SsSsBsBbS', '2': 'SsBbSsSsB', '%': 'SsSbSbSbS', '8': 'BsSbSsBsS', '-': 'SbSsSsBsB', 'Y': 'BbSsBsSsS', 'V': 'SbBsSsSsB', 'I': 'SsBsSbBsS', ' ': 'SbBsSsBsS', 'X': 'SbSsBsSsB'}:
        return{'SsSsBsBbS': 'T', 'SsBbSsSsB': '2', 'SsSbSbSbS': '%', 'BsSbSsBsS': '8', 'SbSsSsBsB': '-', 'BbSsBsSsS': 'Y', 'SbBsSsSsB': 'V', 'SsBsSbBsS': 'I', 'SbBsSsBsS': ' ', 'SbSsBsSsB': 'X'}
    elif a == {'D': 'SbBsSsBsS', 'U': 'BsBbSsSsS', 'M': 'SbSsBsBsS', 'C': 'BsBsSbSsS', 'Y': 'SsBsBbSsS', '.': 'BsSsBbSsS', 'V': 'SbSbSbSsS', '2': 'BbBsSsSsS', 'E': 'SsBbBsSsS'}:
        return{'SbBsSsBsS': 'D', 'BsBbSsSsS': 'U', 'SbSsBsBsS': 'M', 'BsBsSbSsS': 'C', 'SsBsBbSsS': 'Y', 'BsSsBbSsS': '.', 'SbSbSbSsS': 'V', 'BbBsSsSsS': '2', 'SsBbBsSsS': 'E'}
    elif a == {'G': 'SsSsSbBsB', '.': 'BbSsSsBsS', 'H': 'BsSsSbBsS', 'T': 'SsSsBsBbS', 'I': 'SsBsSbBsS', '$': 'SbSbSbSsS', 'E': 'BsSsBbSsS', '8': 'BsSbSsBsS', 'C': 'BsBsSbSsS', 'X': 'SbSsBsSsB', 'Q': 'SsSsSsBbB'}:
        return{'SsSsSbBsB': 'G', 'BbSsSsBsS': '.', 'BsSsSbBsS': 'H', 'SsSsBsBbS': 'T', 'SsBsSbBsS': 'I', 'SbSbSbSsS': '$', 'BsSsBbSsS': 'E', 'BsSbSsBsS': '8', 'BsBsSbSsS': 'C', 'SbSsBsSsB': 'X', 'SsSsSsBbB': 'Q'}
    elif a == {'-': 'BsBsSbSsS', '1': 'SsBbBsSsS', '3': 'SbSsBsSsB', 'Y': 'BbSsSsBsS', '6': 'BsSsSbBsS', 'K': 'SsSsSbBsB', 'D': 'SbSsBsBsS', 'T': 'BbBsSsSsS', 'E': 'SsBsSsSbB', 'G': 'BsBsSsSbS'}:
        return{'BsBsSbSsS': '-', 'SsBbBsSsS': '1', 'SbSsBsSsB': '3', 'BbSsSsBsS': 'Y', 'BsSsSbBsS': '6', 'SsSsSbBsB': 'K', 'SbSsBsBsS': 'D', 'BbBsSsSsS': 'T', 'SsBsSsSbB': 'E', 'BsBsSsSbS': 'G'}
    elif a == {'A': 'SsSsBbSsB', '+': 'BsSsSsSbB', 'J': 'BsSsSbSsB', 'S': 'BbSsBsSsS', 'U': 'SsBsSsBbS', '/': 'SsBsBbSsS', '6': 'SsBbBsSsS', 'I': 'SsBbSsBsS'}:
        return{'SsSsBbSsB': 'A', 'BsSsSsSbB': '+', 'BsSsSbSsB': 'J', 'BbSsBsSsS': 'S', 'SsBsSsBbS': 'U', 'SsBsBbSsS': '/', 'SsBbBsSsS': '6', 'SsBbSsBsS': 'I'}
    elif a == {'5': 'SsBsSsSbB', '-': 'BbBsSsSsS', 'A': 'SsSsBbBsS', 'F': 'SsSsBsSbB', 'B': 'SsBsSbBsS', '7': 'SsSbSsBsB', '6': 'SsSsBbSsB', 'K': 'SsSbSbSbS', 'Y': 'BbSsBsSsS', 'I': 'SsSsSbBsB', 'P': 'SsBsSsBbS'}:
        return{'SsBsSsSbB': '5', 'BbBsSsSsS': '-', 'SsSsBbBsS': 'A', 'SsSsBsSbB': 'F', 'SsBsSbBsS': 'B', 'SsSbSsBsB': '7', 'SsSsBbSsB': '6', 'SsSbSbSbS': 'K', 'BbSsBsSsS': 'Y', 'SsSsSbBsB': 'I', 'SsBsSsBbS': 'P'}
    elif a == {'4': 'SsSbBsSsB', 'V': 'SbBsSsSsB', '+': 'SbSsSbSbS', '8': 'BsSbSsBsS', ' ': 'SbBsSsBsS', 'D': 'SsSsBbSsB', '2': 'SsBbSsSsB', '-': 'SbSsSsBsB', 'P': 'SsBsBsSbS', '/': 'SbSbSsSbS', 'A': 'BsSsSbSsB', '%': 'SsSbSbSbS'}:
        return{'SsSbBsSsB': '4', 'SbBsSsSsB': 'V', 'SbSsSbSbS': '+', 'BsSbSsBsS': '8', 'SbBsSsBsS': ' ', 'SsSsBbSsB': 'D', 'SsBbSsSsB': '2', 'SbSsSsBsB': '-', 'SsBsBsSbS': 'P', 'SbSbSsSbS': '/', 'BsSsSbSsB': 'A', 'SsSbSbSbS': '%'}
    elif a == {'E': 'BsSsBbSsS', '0': 'SsSbBsBsS', 'O': 'BsSsBsSbS', 'K': 'BsSsSsSbB', 'C': 'BsBsSbSsS', '6': 'SsBbBsSsS', 'X': 'SbSsBsSsB'}:
        return{'BsSsBbSsS': 'E', 'SsSbBsBsS': '0', 'BsSsBsSbS': 'O', 'BsSsSsSbB': 'K', 'BsBsSbSsS': 'C', 'SsBbBsSsS': '6', 'SbSsBsSsB': 'X'}
    elif a == {'Q': 'SsSsSsBbB', 'C': 'BsBsSbSsS', 'M': 'BsBsSsSbS', '3': 'BsBbSsSsS', 'X': 'SbSsBsSsB', 'N': 'SsSsBsSbB', '.': 'BbSsSsBsS', ' ': 'SbBsSsBsS', 'A': 'BsSsSbSsB'}:
        return{'SsSsSsBbB': 'Q', 'BsBsSbSsS': 'C', 'BsBsSsSbS': 'M', 'BsBbSsSsS': '3', 'SbSsBsSsB': 'X', 'SsSsBsSbB': 'N', 'BbSsSsBsS': '.', 'SbBsSsBsS': ' ', 'BsSsSbSsB': 'A'}
    elif a == {'V': 'SbBsSsSsB', 'A': 'BsSsSbSsB', 'H': 'BsSsSbBsS', 'K': 'BsSsSsSbB', 'X': 'SbSsBsSsB', 'M': 'BsBsSsSbS', 'Z': 'SbBsBsSsS', 'N': 'SsSsBsSbB', '%': 'SsSbSbSbS', 'L': 'SsBsSsSbB', 'O': 'BsSsBsSbS', 'I': 'SsBsSbBsS'}:
        return{'SbBsSsSsB': 'V', 'BsSsSbSsB': 'A', 'BsSsSbBsS': 'H', 'BsSsSsSbB': 'K', 'SbSsBsSsB': 'X', 'BsBsSsSbS': 'M', 'SbBsBsSsS': 'Z', 'SsSsBsSbB': 'N', 'SsSbSbSbS': '%', 'SsBsSsSbB': 'L', 'BsSsBsSbS': 'O', 'SsBsSbBsS': 'I'}
    elif a == {'H': 'BsSsSbBsS', '2': 'SsBbSsSsB', 'V': 'SbBsSsSsB', 'Q': 'SsSsSsBbB', '6': 'SsBbBsSsS', 'W': 'BbBsSsSsS'}:
        return{'BsSsSbBsS': 'H', 'SsBbSsSsB': '2', 'SbBsSsSsB': 'V', 'SsSsSsBbB': 'Q', 'SsBbBsSsS': '6', 'BbBsSsSsS': 'W'}
    elif a == {'E': 'BsSsBbSsS', 'P': 'SsBsBsSbS', '1': 'BsSbSsSsB', '*': 'SbSsBsBsS', '+': 'SbSsSbSbS', '9': 'SsBbSsBsS', 'R': 'BsSsSsBbS', '0': 'SsSbBsBsS', 'G': 'SsSsSbBsB'}:
        return{'BsSsBbSsS': 'E', 'SsBsBsSbS': 'P', 'BsSbSsSsB': '1', 'SbSsBsBsS': '*', 'SbSsSbSbS': '+', 'SsBbSsBsS': '9', 'BsSsSsBbS': 'R', 'SsSbBsBsS': '0', 'SsSsSbBsB': 'G'}
    elif a == {'Q': 'SsSsSsBbB', '*': 'SbSsBsBsS', 'H': 'BsSsSbBsS', ' ': 'SbBsSsBsS', 'O': 'BsSsBsSbS', 'U': 'BbSsSsSsB', 'R': 'BsSsSsBbS'}:
        return{'SsSsSsBbB': 'Q', 'SbSsBsBsS': '*', 'BsSsSbBsS': 'H', 'SbBsSsBsS': ' ', 'BsSsBsSbS': 'O', 'BbSsSsSsB': 'U', 'BsSsSsBbS': 'R'}
    elif a == {'T': 'SsSsBsBbS', 'W': 'BbBsSsSsS', '5': 'BsSbBsSsS', 'Z': 'SbBsBsSsS', 'P': 'SsBsBsSbS', 'I': 'SsBsSbBsS', '7': 'SsSbSsBsB', 'M': 'BsBsSsSbS', ' ': 'SbBsSsBsS'}:
        return{'SsSsBsBbS': 'T', 'BbBsSsSsS': 'W', 'BsSbBsSsS': '5', 'SbBsBsSsS': 'Z', 'SsBsBsSbS': 'P', 'SsBsSbBsS': 'I', 'SsSbSsBsB': '7', 'BsBsSsSbS': 'M', 'SbBsSsBsS': ' '}
    elif a == {'/': 'SsSsBsBbS', 'X': 'BsBbSsSsS', '9': 'SsBsSbBsS', '1': 'SsSsSbBsB', 'M': 'SsSbSsBsB', '*': 'SsBbSsSsB', 'W': 'BsSsSsBbS', 'Q': 'BsSsBsSbS', '%': 'SsBsSbSsB', 'S': 'BsBsSsSbS'}:
        return{'SsSsBsBbS': '/', 'BsBbSsSsS': 'X', 'SsBsSbBsS': '9', 'SsSsSbBsB': '1', 'SsSbSsBsB': 'M', 'SsBbSsSsB': '*', 'BsSsSsBbS': 'W', 'BsSsBsSbS': 'Q', 'SsBsSbSsB': '%', 'BsBsSsSbS': 'S'}
    elif a == {'%': 'SbBsSsSsB', '0': 'SsSsSsBbB', '/': 'SbSbSbSsS', ' ': 'BbSsBsSsS', 'G': 'BsSbSsSsB', '7': 'SsBbBsSsS', '3': 'SsBsBbSsS', 'I': 'SsSbBsBsS', '4': 'BsBbSsSsS', 'D': 'SsBbSsSsB'}:
        return{'SbBsSsSsB': '%', 'SsSsSsBbB': '0', 'SbSbSbSsS': '/', 'BbSsBsSsS': ' ', 'BsSbSsSsB': 'G', 'SsBbBsSsS': '7', 'SsBsBbSsS': '3', 'SsSbBsBsS': 'I', 'BsBbSsSsS': '4', 'SsBbSsSsB': 'D'}
    elif a == {'F': 'SsSsSbBsB', 'O': 'SsSsSsBbB', 'R': 'SbSsBsSsB', 'U': 'SbSsSbSbS', 'C': 'BsSbSsSsB', 'N': 'SsBbSsSsB', ' ': 'SsBsSsSbB', 'V': 'SbSbSbSsS'}:
        return{'SsSsSbBsB': 'F', 'SsSsSsBbB': 'O', 'SbSsBsSsB': 'R', 'SbSsSbSbS': 'U', 'BsSbSsSsB': 'C', 'SsBbSsSsB': 'N', 'SsBsSsSbB': ' ', 'SbSbSbSsS': 'V'}
    elif a == {'F': 'SsBsBbSsS', 'V': 'SbBsSsSsB', 'E': 'SbSbSbSsS', '-': 'SsSsBbBsS', 'B': 'SsSbBsSsB', 'G': 'SsSbBsBsS', 'K': 'SsBsBsSbS'}:
        return{'SsBsBbSsS': 'F', 'SbBsSsSsB': 'V', 'SbSbSbSsS': 'E', 'SsSsBbBsS': '-', 'SsSbBsSsB': 'B', 'SsSbBsBsS': 'G', 'SsBsBsSbS': 'K'}
    elif a == {'6': 'SsBbBsSsS', 'M': 'BsBsSsSbS', 'Q': 'SsSsSsBbB', 'P': 'SsBsBsSbS', '+': 'SbSsSbSbS', 'J': 'SsSsBbBsS', 'V': 'SbBsSsSsB', '.': 'BbSsSsBsS'}:
        return{'SsBbBsSsS': '6', 'BsBsSsSbS': 'M', 'SsSsSsBbB': 'Q', 'SsBsBsSbS': 'P', 'SbSsSbSbS': '+', 'SsSsBbBsS': 'J', 'SbBsSsSsB': 'V', 'BbSsSsBsS': '.'}
    elif a == {'%': 'SsSbSbSbS', '*': 'SbSsBsBsS', 'D': 'SsSsBbSsB', 'I': 'SsBsSbBsS', '2': 'SsBbSsSsB', 'G': 'SsSsSbBsB', 'U': 'BbSsSsSsB', 'R': 'BsSsSsBbS', 'E': 'BsSsBbSsS', 'B': 'SsBsSbSsB', 'P': 'SsBsBsSbS'}:
        return{'SsSbSbSbS': '%', 'SbSsBsBsS': '*', 'SsSsBbSsB': 'D', 'SsBsSbBsS': 'I', 'SsBbSsSsB': '2', 'SsSsSbBsB': 'G', 'BbSsSsSsB': 'U', 'BsSsSsBbS': 'R', 'BsSsBbSsS': 'E', 'SsBsSbSsB': 'B', 'SsBsBsSbS': 'P'}
    elif a == {'C': 'BsBsSbSsS', 'T': 'SsSsBsBbS', 'Y': 'BbSsBsSsS', 'S': 'SsBsSsBbS', ' ': 'SbBsSsBsS', 'F': 'SsBsBbSsS', 'U': 'BbSsSsSsB', 'A': 'BsSsSbSsB', '%': 'SsSbSbSbS', 'E': 'BsSsBbSsS', 'J': 'SsSsBbBsS', '/': 'SbSbSsSbS'}:
        return{'BsBsSbSsS': 'C', 'SsSsBsBbS': 'T', 'BbSsBsSsS': 'Y', 'SsBsSsBbS': 'S', 'SbBsSsBsS': ' ', 'SsBsBbSsS': 'F', 'BbSsSsSsB': 'U', 'BsSsSbSsB': 'A', 'SsSbSbSbS': '%', 'BsSsBbSsS': 'E', 'SsSsBbBsS': 'J', 'SbSbSsSbS': '/'}
    elif a == {'X': 'SbSsBsSsB', '.': 'BbSsSsBsS', '1': 'BsSbSsSsB', 'N': 'SsSsBsSbB', '4': 'SsSbBsSsB', '$': 'SbSbSbSsS', '2': 'SsBbSsSsB', 'P': 'SsBsBsSbS', 'I': 'SsBsSbBsS', 'W': 'BbBsSsSsS', '6': 'SsBbBsSsS'}:
        return{'SbSsBsSsB': 'X', 'BbSsSsBsS': '.', 'BsSbSsSsB': '1', 'SsSsBsSbB': 'N', 'SsSbBsSsB': '4', 'SbSbSbSsS': '$', 'SsBbSsSsB': '2', 'SsBsBsSbS': 'P', 'SsBsSbBsS': 'I', 'BbBsSsSsS': 'W', 'SsBbBsSsS': '6'}
    elif a == {'P': 'SsBsBsSbS', '7': 'SsSbSsBsB', 'M': 'BsBsSsSbS', 'G': 'SsSsSbBsB', 'X': 'SbSsBsSsB', 'U': 'BbSsSsSsB', 'F': 'SsBsBbSsS'}:
        return{'SsBsBsSbS': 'P', 'SsSbSsBsB': '7', 'BsBsSsSbS': 'M', 'SsSsSbBsB': 'G', 'SbSsBsSsB': 'X', 'BbSsSsSsB': 'U', 'SsBsBbSsS': 'F'}
    elif a == {'N': 'SsBsBbSsS', '.': 'SsBsBsSbS', 'A': 'SbSsSbSbS', '+': 'SsSsSsBbB', 'J': 'SsBbSsSsB', 'F': 'SsSsSbBsB', 'Y': 'SsBbBsSsS', 'D': 'SbSsBsSsB', '%': 'BbSsSsSsB', '*': 'BsSsSsBbS', 'W': 'SsBbSsBsS', '8': 'BsBsSsSbS'}:
        return{'SsBsBbSsS': 'N', 'SsBsBsSbS': '.', 'SbSsSbSbS': 'A', 'SsSsSsBbB': '+', 'SsBbSsSsB': 'J', 'SsSsSbBsB': 'F', 'SsBbBsSsS': 'Y', 'SbSsBsSsB': 'D', 'BbSsSsSsB': '%', 'BsSsSsBbS': '*', 'SsBbSsBsS': 'W', 'BsBsSsSbS': '8'}
    elif a == {'Q': 'SbBsSsSsB', 'Z': 'SsBsSsSbB', 'T': 'SsSbSbSbS', '3': 'BbBsSsSsS', 'O': 'SsSbBsBsS', 'L': 'SsBsSbBsS', '5': 'BsBsSbSsS'}:
        return{'SbBsSsSsB': 'Q', 'SsBsSsSbB': 'Z', 'SsSbSbSbS': 'T', 'BbBsSsSsS': '3', 'SsSbBsBsS': 'O', 'SsBsSbBsS': 'L', 'BsBsSbSsS': '5'}
    elif a == {'5': 'BsSbBsSsS', 'T': 'SsSsBsBbS', '0': 'SsSbBsBsS', '7': 'SsSbSsBsB', 'Y': 'BbSsBsSsS', '*': 'SbSsBsBsS', '-': 'SbSsSsBsB', 'F': 'SsBsBbSsS', 'Z': 'SbBsBsSsS', 'V': 'SbBsSsSsB'}:
        return{'BsSbBsSsS': '5', 'SsSsBsBbS': 'T', 'SsSbBsBsS': '0', 'SsSbSsBsB': '7', 'BbSsBsSsS': 'Y', 'SbSsBsBsS': '*', 'SbSsSsBsB': '-', 'SsBsBbSsS': 'F', 'SbBsBsSsS': 'Z', 'SbBsSsSsB': 'V'}
    elif a == {'8': 'BsSbSsBsS', '5': 'BsSbBsSsS', 'F': 'SsBsBbSsS', 'I': 'SsBsSbBsS', '%': 'SsSbSbSbS', 'W': 'BbBsSsSsS', '0': 'SsSbBsBsS'}:
        return{'BsSbSsBsS': '8', 'BsSbBsSsS': '5', 'SsBsBbSsS': 'F', 'SsBsSbBsS': 'I', 'SsSbSbSbS': '%', 'BbBsSsSsS': 'W', 'SsSbBsBsS': '0'}
    elif a == {'R': 'SsSbSbSbS', 'H': 'SsBsSbBsS', 'E': 'BsBsSbSsS', 'W': 'SsSsSbBsB', '1': 'SsSsBsSbB', 'G': 'SsBbSsBsS'}:
        return{'SsSbSbSbS': 'R', 'SsBsSbBsS': 'H', 'BsBsSbSsS': 'E', 'SsSsSbBsB': 'W', 'SsSsBsSbB': '1', 'SsBbSsBsS': 'G'}
    elif a == {'Y': 'BbSsBsSsS', 'G': 'SsSsSbBsB', 'Z': 'SbBsBsSsS', 'B': 'SsBsSbSsB', '2': 'SsBbSsSsB', '8': 'BsSbSsBsS', 'A': 'BsSsSbSsB', 'F': 'SsBsBbSsS', '0': 'SsSbBsBsS', 'Q': 'SsSsSsBbB', 'N': 'SsSsBsSbB', 'L': 'SsBsSsSbB'}:
        return{'BbSsBsSsS': 'Y', 'SsSsSbBsB': 'G', 'SbBsBsSsS': 'Z', 'SsBsSbSsB': 'B', 'SsBbSsSsB': '2', 'BsSbSsBsS': '8', 'BsSsSbSsB': 'A', 'SsBsBbSsS': 'F', 'SsSbBsBsS': '0', 'SsSsSsBbB': 'Q', 'SsSsBsSbB': 'N', 'SsBsSsSbB': 'L'}
    elif a == {'5': 'SbSsBsSsB', 'L': 'BsSsSsBbS', 'F': 'SsSbSbSbS', 'U': 'SsSsBbBsS', 'R': 'BbBsSsSsS', '4': 'SsSsSbBsB', '.': 'SsBsSsBbS'}:
        return{'SbSsBsSsB': '5', 'BsSsSsBbS': 'L', 'SsSbSbSbS': 'F', 'SsSsBbBsS': 'U', 'BbBsSsSsS': 'R', 'SsSsSbBsB': '4', 'SsBsSsBbS': '.'}
    elif a == {'8': 'BsSbSsBsS', '1': 'BsSbSsSsB', 'U': 'BbSsSsSsB', 'J': 'SsSsBbBsS', '/': 'SbSbSsSbS', '$': 'SbSbSbSsS', '3': 'BsBbSsSsS'}:
        return{'BsSbSsBsS': '8', 'BsSbSsSsB': '1', 'BbSsSsSsB': 'U', 'SsSsBbBsS': 'J', 'SbSbSsSbS': '/', 'SbSbSbSsS': '$', 'BsBbSsSsS': '3'}
    elif a == {'7': 'SsSbSsBsB', 'H': 'BsSsSbBsS', '-': 'SbSsSsBsB', 'A': 'BsSsSbSsB', 'D': 'SsSsBbSsB', 'Y': 'BbSsBsSsS', '6': 'SsBbBsSsS', 'I': 'SsBsSbBsS', 'Z': 'SbBsBsSsS'}:
        return{'SsSbSsBsB': '7', 'BsSsSbBsS': 'H', 'SbSsSsBsB': '-', 'BsSsSbSsB': 'A', 'SsSsBbSsB': 'D', 'BbSsBsSsS': 'Y', 'SsBbBsSsS': '6', 'SsBsSbBsS': 'I', 'SbBsBsSsS': 'Z'}
    elif a == {'W': 'SbSsBsBsS', 'R': 'SbSsBsSsB', 'A': 'BsSsSsSbB', '0': 'SbSsSbSbS', '$': 'SsSsBsBbS', '9': 'SsSsBbBsS', 'K': 'BsSsSbSsB', 'U': 'BsSbBsSsS', 'O': 'SsBsSsSbB', 'Z': 'SbSbSsSbS'}:
        return{'SbSsBsBsS': 'W', 'SbSsBsSsB': 'R', 'BsSsSsSbB': 'A', 'SbSsSbSbS': '0', 'SsSsBsBbS': '$', 'SsSsBbBsS': '9', 'BsSsSbSsB': 'K', 'BsSbBsSsS': 'U', 'SsBsSsSbB': 'O', 'SbSbSsSbS': 'Z'}
    elif a == {'%': 'SsSbSbSbS', 'F': 'SsBsBbSsS', '-': 'SbSsSsBsB', 'T': 'SsSsBsBbS', 'G': 'SsSsSbBsB', 'B': 'SsBsSbSsB'}:
        return{'SsSbSbSbS': '%', 'SsBsBbSsS': 'F', 'SbSsSsBsB': '-', 'SsSsBsBbS': 'T', 'SsSsSbBsB': 'G', 'SsBsSbSsB': 'B'}
    elif a == {'%': 'SsBsSsBbS', '.': 'SsSbSbSbS', '8': 'BbBsSsSsS', 'M': 'BsSsSbBsS', 'C': 'SsSsSbBsB', 'R': 'SbSsSbSbS', 'P': 'BsSbBsSsS', 'U': 'BsSsBsSbS', '*': 'SbSbSsSbS', 'W': 'SsSsBbBsS', '5': 'SbSsBsSsB', ' ': 'SsBbSsBsS'}:
        return{'SsBsSsBbS': '%', 'SsSbSbSbS': '.', 'BbBsSsSsS': '8', 'BsSsSbBsS': 'M', 'SsSsSbBsB': 'C', 'SbSsSbSbS': 'R', 'BsSbBsSsS': 'P', 'BsSsBsSbS': 'U', 'SbSbSsSbS': '*', 'SsSsBbBsS': 'W', 'SbSsBsSsB': '5', 'SsBbSsBsS': ' '}
    elif a == {' ': 'SbBsSsBsS', 'D': 'SsSsBbSsB', 'B': 'SsBsSbSsB', '+': 'SbSsSbSbS', '-': 'SbSsSsBsB', '$': 'SbSbSbSsS', '1': 'BsSbSsSsB', '9': 'SsBbSsBsS', 'V': 'SbBsSsSsB', 'S': 'SsBsSsBbS'}:
        return{'SbBsSsBsS': ' ', 'SsSsBbSsB': 'D', 'SsBsSbSsB': 'B', 'SbSsSbSbS': '+', 'SbSsSsBsB': '-', 'SbSbSbSsS': '$', 'BsSbSsSsB': '1', 'SsBbSsBsS': '9', 'SbBsSsSsB': 'V', 'SsBsSsBbS': 'S'}
    elif a == {'W': 'BbBsSsSsS', '.': 'BbSsSsBsS', '4': 'SsSbBsSsB', 'K': 'BsSsSsSbB', '*': 'SbSsBsBsS', 'Q': 'SsSsSsBbB', 'M': 'BsBsSsSbS', '6': 'SsBbBsSsS', 'T': 'SsSsBsBbS', 'G': 'SsSsSbBsB', 'C': 'BsBsSbSsS'}:
        return{'BbBsSsSsS': 'W', 'BbSsSsBsS': '.', 'SsSbBsSsB': '4', 'BsSsSsSbB': 'K', 'SbSsBsBsS': '*', 'SsSsSsBbB': 'Q', 'BsBsSsSbS': 'M', 'SsBbBsSsS': '6', 'SsSsBsBbS': 'T', 'SsSsSbBsB': 'G', 'BsBsSbSsS': 'C'}
    elif a == {'Q': 'SsSsSsBbB', '7': 'SsSbSsBsB', 'H': 'BsSsSbBsS', 'X': 'SbSsBsSsB', '6': 'SsBbBsSsS', '*': 'SbSsBsBsS', 'Z': 'SbBsBsSsS', 'Y': 'BbSsBsSsS', 'A': 'BsSsSbSsB', '$': 'SbSbSbSsS', 'L': 'SsBsSsSbB', 'F': 'SsBsBbSsS'}:
        return{'SsSsSsBbB': 'Q', 'SsSbSsBsB': '7', 'BsSsSbBsS': 'H', 'SbSsBsSsB': 'X', 'SsBbBsSsS': '6', 'SbSsBsBsS': '*', 'SbBsBsSsS': 'Z', 'BbSsBsSsS': 'Y', 'BsSsSbSsB': 'A', 'SbSbSbSsS': '$', 'SsBsSsSbB': 'L', 'SsBsBbSsS': 'F'}
    elif a == {'P': 'SbSsSbSbS', '1': 'SbSsBsSsB', 'Z': 'SsSsSsBbB', '-': 'SsBsSbBsS', 'X': 'SbBsBsSsS', '5': 'SsBbSsBsS', 'G': 'SsBbBsSsS', '*': 'SsSsBsBbS', 'S': 'SbBsSsBsS', '$': 'BsSsSsSbB'}:
        return{'SbSsSbSbS': 'P', 'SbSsBsSsB': '1', 'SsSsSsBbB': 'Z', 'SsBsSbBsS': '-', 'SbBsBsSsS': 'X', 'SsBbSsBsS': '5', 'SsBbBsSsS': 'G', 'SsSsBsBbS': '*', 'SbBsSsBsS': 'S', 'BsSsSsSbB': '$'}
    elif a == {'/': 'SbSbSsSbS', 'A': 'BsSsSbSsB', 'V': 'SbBsSsSsB', '.': 'BbSsSsBsS', 'H': 'BsSsSbBsS', '6': 'SsBbBsSsS', '8': 'BsSbSsBsS', '$': 'SbSbSbSsS', 'L': 'SsBsSsSbB', 'O': 'BsSsBsSbS', 'D': 'SsSsBbSsB', '5': 'BsSbBsSsS'}:
        return{'SbSbSsSbS': '/', 'BsSsSbSsB': 'A', 'SbBsSsSsB': 'V', 'BbSsSsBsS': '.', 'BsSsSbBsS': 'H', 'SsBbBsSsS': '6', 'BsSbSsBsS': '8', 'SbSbSbSsS': '$', 'SsBsSsSbB': 'L', 'BsSsBsSbS': 'O', 'SsSsBbSsB': 'D', 'BsSbBsSsS': '5'}
    elif a == {'G': 'SsSsBsBbS', 'T': 'SbBsSsSsB', 'M': 'BsSbBsSsS', 'P': 'SsBsBsSbS', '6': 'BsBbSsSsS', 'B': 'BbSsBsSsS'}:
        return{'SsSsBsBbS': 'G', 'SbBsSsSsB': 'T', 'BsSbBsSsS': 'M', 'SsBsBsSbS': 'P', 'BsBbSsSsS': '6', 'BbSsBsSsS': 'B'}
    elif a == {'/': 'SbSbSsSbS', '-': 'SbSsSsBsB', '5': 'BsSbBsSsS', 'D': 'SsSsBbSsB', 'P': 'SsBsBsSbS', 'O': 'BsSsBsSbS'}:
        return{'SbSbSsSbS': '/', 'SbSsSsBsB': '-', 'BsSbBsSsS': '5', 'SsSsBbSsB': 'D', 'SsBsBsSbS': 'P', 'BsSsBsSbS': 'O'}
    elif a == {'4': 'SsBsSbBsS', '0': 'SsBsSbSsB', '1': 'BbSsSsSsB', 'N': 'BsSsBbSsS', 'E': 'SbSsBsBsS', '2': 'SsBsBsSbS', '6': 'BbSsBsSsS', 'Q': 'BsBbSsSsS', 'R': 'SbBsSsSsB', 'V': 'SsBbSsSsB', 'O': 'BsSsSsBbS', 'K': 'SbSsBsSsB'}:
        return{'SsBsSbBsS': '4', 'SsBsSbSsB': '0', 'BbSsSsSsB': '1', 'BsSsBbSsS': 'N', 'SbSsBsBsS': 'E', 'SsBsBsSbS': '2', 'BbSsBsSsS': '6', 'BsBbSsSsS': 'Q', 'SbBsSsSsB': 'R', 'SsBbSsSsB': 'V', 'BsSsSsBbS': 'O', 'SbSsBsSsB': 'K'}
    elif a == {'G': 'SsSsSbBsB', 'A': 'BsSsSbSsB', '.': 'BbSsSsBsS', 'P': 'SsBsBsSbS', 'L': 'SsBsSsSbB', 'K': 'BsSsSsSbB', 'Z': 'SbBsBsSsS', '+': 'SbSsSbSbS', ' ': 'SbBsSsBsS', '9': 'SsBbSsBsS', 'V': 'SbBsSsSsB', 'H': 'BsSsSbBsS'}:
        return{'SsSsSbBsB': 'G', 'BsSsSbSsB': 'A', 'BbSsSsBsS': '.', 'SsBsBsSbS': 'P', 'SsBsSsSbB': 'L', 'BsSsSsSbB': 'K', 'SbBsBsSsS': 'Z', 'SbSsSbSbS': '+', 'SbBsSsBsS': ' ', 'SsBbSsBsS': '9', 'SbBsSsSsB': 'V', 'BsSsSbBsS': 'H'}
    elif a == {'V': 'SbSsSbSbS', 'B': 'BsBbSsSsS', '7': 'SsSbBsBsS', '0': 'SbBsSsSsB', 'E': 'BsSbSsBsS', '8': 'SbSbSbSsS', '3': 'SsSbSsBsB', '4': 'BsSsBsSbS', 'S': 'BbSsBsSsS', 'F': 'BbSsSsSsB', '*': 'BsBsSsSbS', 'J': 'SsBbSsSsB'}:
        return{'SbSsSbSbS': 'V', 'BsBbSsSsS': 'B', 'SsSbBsBsS': '7', 'SbBsSsSsB': '0', 'BsSbSsBsS': 'E', 'SbSbSbSsS': '8', 'SsSbSsBsB': '3', 'BsSsBsSbS': '4', 'BbSsBsSsS': 'S', 'BbSsSsSsB': 'F', 'BsBsSsSbS': '*', 'SsBbSsSsB': 'J'}
    elif a == {'C': 'SbSsBsSsB', 'Y': 'BsSbSsSsB', '-': 'BsSsBsSbS', '/': 'BsSsSsSbB', '%': 'SsBbBsSsS', '1': 'SsSsBsSbB'}:
        return{'SbSsBsSsB': 'C', 'BsSbSsSsB': 'Y', 'BsSsBsSbS': '-', 'BsSsSsSbB': '/', 'SsBbBsSsS': '%', 'SsSsBsSbB': '1'}
    elif a == {'4': 'SsBsSsBbS', '2': 'SbBsSsBsS', 'A': 'SsSsSsBbB', 'Q': 'SsSsBsSbB', '/': 'SbBsBsSsS', 'V': 'BsBbSsSsS', '6': 'SbSsSbSbS', 'C': 'SsBsSsSbB', 'H': 'BbSsSsSsB', 'N': 'BbSsSsBsS'}:
        return{'SsBsSsBbS': '4', 'SbBsSsBsS': '2', 'SsSsSsBbB': 'A', 'SsSsBsSbB': 'Q', 'SbBsBsSsS': '/', 'BsBbSsSsS': 'V', 'SbSsSbSbS': '6', 'SsBsSsSbB': 'C', 'BbSsSsSsB': 'H', 'BbSsSsBsS': 'N'}
    elif a == {'X': 'SbSsBsSsB', 'B': 'SsBsBsSbS', 'S': 'SsSsBsSbB', 'N': 'SsSbSsBsB', 'Q': 'SbSsSsBsB', '6': 'SbBsSsSsB', 'L': 'BsSsSbBsS', '*': 'SsBbSsBsS', 'C': 'SbBsSsBsS'}:
        return{'SbSsBsSsB': 'X', 'SsBsBsSbS': 'B', 'SsSsBsSbB': 'S', 'SsSbSsBsB': 'N', 'SbSsSsBsB': 'Q', 'SbBsSsSsB': '6', 'BsSsSbBsS': 'L', 'SsBbSsBsS': '*', 'SbBsSsBsS': 'C'}
    elif a == {'W': 'BbBsSsSsS', 'O': 'BsSsBsSbS', 'P': 'SsBsBsSbS', 'U': 'BbSsSsSsB', 'D': 'SsSsBbSsB', 'C': 'BsBsSbSsS', '%': 'SsSbSbSbS', '+': 'SbSsSbSbS', 'A': 'BsSsSbSsB', '0': 'SsSbBsBsS', 'E': 'BsSsBbSsS', 'I': 'SsBsSbBsS'}:
        return{'BbBsSsSsS': 'W', 'BsSsBsSbS': 'O', 'SsBsBsSbS': 'P', 'BbSsSsSsB': 'U', 'SsSsBbSsB': 'D', 'BsBsSbSsS': 'C', 'SsSbSbSbS': '%', 'SbSsSbSbS': '+', 'BsSsSbSsB': 'A', 'SsSbBsBsS': '0', 'BsSsBbSsS': 'E', 'SsBsSbBsS': 'I'}
    else:
        return{'SsBsSbBsS': '2', 'SsBsSsSbB': '5', 'BbBsSsSsS': ' ', 'SsBbSsBsS': '7', 'SsSbBsSsB': '+', 'SsBsBbSsS': 'B'}
def code39(a, key):
    if a =='Sulfur, so good.':
        return'SsSbSsBsBsBsSsSsSbBsBsSsBbSsSsSsSsBsSbBsBsSsSsSbBsSsSbBsSsBsBsSbSsBsSsSsSbSbSbSsSsSbSsBsBsSsBsSbBsSsSsSbSbSbSsSbBsSsSsBsSsBsSbBsSsSsBsSbBsSsSbSsBsSsBsSbSbSsSbS'
    if a =='I hit my neon the table.':
        return'BsSsBsSbSsBsSsSsSbBsBbBsSsSsSsBsSsBsSbSsSbBsSsSsBsBsSsSsSbBsSsSsBbSsBsBsBbSsSsSsBsSsSsSbBsBsSsSbSsBsBsSsSsBbSsBbSsBsSsSsBsSsSbSsBsBsSsSsSbBsSbBsSsSsBsBbBsSsSsSsBsSsSsBbSsBsSsSsSbBsSbBsSsSsBsBsSbBsSsSsSbSsSsBsBsSsSbSbSbSsBsSsSsBbSsBsSbSsSsB'
    if a =='Tellurium going to the store.':
        return'SsSsSbBsBsBsSsBsSbSsBsBsSbSsSsBsBsSbSsSsSsBbSsSsBsSbSsBsSsBsSsSsBsBbSsSsBbSsSsBsSsBsSbSsBsBsSsSbBsSsSsBsSsBbSsBbSsSsBsSsSsSsBsBbSsSsBsSsSbBsSsBsSsBbSsBsSsSbBsSsSsSsSbBsBsBbSsSsBsSsBsSsSbBsSsSsSsSbBsBsSsSsSsBbBsBsSsBsSbSsBsSsSbBsSsSbSsSbSbSsSsSsSbBsBsBbSsSsBsSsSbSsBsSsBsBsSsBsSbSsSbSsSsBsB'
    if a =="Slow down. You're going to phosphorus.":
        return'BbSsSsBsSsBbSsSsSsBsBsBsSsSbSsSsSbBsSsBsBsSsBbSsSsSbSsBsSsBsBsBsSsSbSsSsSbBsSsBsBsBsSbSsSsSbBsSsSsBsBsSsBbSsSsBsSbBsSsSsBsBsSsSbSsSsSsBbSsBsSsBbBsSsSsSsSsBsSbBsSsSsBsBbSsBsSsBbSsSsSbSbSbSsSsBsBsSsSbSsBsSsSsBbSsBsBsSbSsSsSbSbSbSsSsBsSsBbSsSsSsBbSsBsSsBsBsSsSbSsBsSsBbSsSsSsBsSsSbBsSsSbSbSbSsBsBsSsSbSsBbSsSsBsSsSsBsSsSbBsSsSbSbSbSsBsBsSsSbSsSsSsBsSbBsSsSsBbSsBsBbSsSsBsSsSbBsSsSsB'
    if a =='It was a long trek, but the hikers boron.':
        return'SbSbSsSbSsSsBbSsSsBsBbBsSsSsSsSsSsSbBsBsBsSsBsSbSsBsSbSsSsBsBbBsSsSsSsBsSsBsSbSsBbBsSsSsSsBsSsSsBbSsSbSbSbSsSsSsBsSbBsSsBsSsSsSbBsBbBsSsSsSsSsBbSsSsBsBsSbBsSsSsSsBbBsSsSsBbSsBsSsSsSbSsSsBsBsBbBsSsSsSsSsSbBsSsBsBsSsBbSsSsSsBbSsSsBsBbBsSsSsSsSsBbSsSsBsSbSsSbSbSsSsBbBsSsSsBbBsSsSsSsSbSsSbSbSsSbSbSsSbSsBbSsBsSsSsSsBbBsSsSsBsSbBsSsSsBsSbSsSsBsBbBsSsSsSsSsSbBsSsBsSbSbSbSsSsBsSbBsSsSsSbSbSbSsSsSsBsSbBsSsBsBsSbSsS'
    if a =='Elsa just washed the fluorine the kitchen.':
        return'SbSsBsSsBsBsSsBsSbSsSsSbBsBsSsBbSsSsBsSsSsBsBbSsSsBsSbSsBsSsSsBbSsSsBsSsSbBsBsSsSsSbSsBsBsSsBsBbSsSsBsSbSsSsBsBbSsSsBsSsSsSbBsBsSsSsSsBsSbBsSbSsBsSsBsBsBsSsSbSsSsBsBbSsSsSsSbSsBsBsSsSsBsSbBsSbSsBsSsBsSsBsBbSsSsSbSsBsBsSsBsSsBsSbSsSsBbSsSsBsSbSbSbSsSsSsSsSbBsBsBsSsSbSsBsBsSsBbSsSsSbSsBsSsBsSsBsBbSsSsSsSbSsBsBsSsSsBsSbBsSbSsBsSsBsSsBsBbSsSsSsBsBsSbSsBsSsSbSsBsSsSbSsBsBsSsSsSsBbBsSsSsBsSbBsSbSsBsSsBsBsSsBbSsSsSbSsSbSbS'
    if a =="It's not mature to throw a temper tantalum.":
        return'SsBsSsBbSsSsSbSsBsBsBsBbSsSsSsSsBbSsSsBsSsBsSbBsSsSsBsSbSsBsSbSsBsBsSsSsSbSsBsBsSsBsSbBsSsSsBsBbSsSsBbSsSsBsSsSsSbSsBsBsBsBsSsSbSsBsSbBsSsSsSbBsSsBsSsSsBsSbBsSsSsSbSsBsBsSbSsBsBsSsSsBsSbBsSsSsSbSsBsBsSsSbBsSsBsBsSbBsSsSsSbSsBsBsSsBbSsSsSsBsSsBsSbBsSsBbSsSsBsSsSsBsSbBsSsSsSbSsBsBsSbBsSsBsSsSsBsBbSsSsSsBbBsSsSsSbBsSsBsSsBsSbBsSsSsSsBsSbBsSsSsSbSsBsBsBbSsSsBsSsSsBsSbSsBsSsSbSsBsBsBbSsSsBsSsSbBsBsSsSsBsBsSsSbSsSsBsBbSsSsSsSsSsBbB'
    if a =='Bring the pictures over here and let calcium.':
        return'BbSsSsBsSsSbSbSsSbSsSsBbSsSsBsSsBbSsBsSsSsBsSbSsBsBbSsBsSsSsSsSbSbSbSsBsSbBsSsSsBsSsBsSbSsBbSsBsSsSsSbSbSbSsSsSsBbSsSsBsSsSsBsSbBsSsSbSbSbSsSsSsSbBsBsSbSbSsSbSsBsSsBsSbSsSbBsSsSsBsBbSsBsSsSsSsBsBsSbSsSsBsSsSbBsBsSsBsSbSsSbSbSsSbSsBbSsBsSsSsBsSbBsSsSsBsSsBsSbSsSbSbSsSbSsBsSsBsSbSsBbSsBsSsSsSbSsSsBsBsSsBbSsBsSsSsBsSbBsSsBbSsBsSsSsBsSbSsBsSsBsSsBsSbSsSsSbSbSbSsBbSsBsSsSsSsSsBsSbBsSbSsSsBsBsBsSbSsBsSsSsSsBsSbBsSsBbSsSsBsSsSsSbBsBsSsSsBbBsSsSbBsBsSsS'
    if a =='He wanted to buy my CDs, but I already sodium.':
        return'SbSsBsSsBsBsSsSsSbBsSsSbSbSbSsBbSsSsBsSsBbSsSsSsBsSsSsSbBsBsBbSsBsSsSsBsSsSsSbBsBsSbSsBsSsSsSbSbSbSsBbSsBsSsSsSbBsSsBsSsSsSbSbSbSsBbBsSsSsSsSsSsSsBbBsSsBsSbSsBsSsSbSbSbSsSsSsBbBsSsSsBsSbSsBsSsSbSbSbSsBsSsBbSsSsBsSbSsBsSsSsBsSsBbSsSbSbSsSbSsSsSbSbSbSsBbBsSsSsSsSsSsSsBbBsBbSsBsSsSsSsSbSbSbSsSsBbBsSsSsSsSbSbSbSsBbSsSsSsBsBsSbSsSsBsSsSsBbSsBsBsSsSsSbBsBbSsSsSsBsBsSbSsBsSsSsBsSbSsBsSsSbSbSbSsSsBsSsBbSsSbBsSsBsSsBsSbSsBsSsSsBbBsSsSsSsSsSsBbBsSsSsBbBsSsBsSsBsSbS'
    if a =="It's stopped raining, so you can get radium brella.":
        return'SsSsSsBbBsSsSbBsBsSsBsBbSsSsSsSsBsSsBbSsSbBsSsBsSsSsBsSsBbSsSsSbBsBsSsBsSsBsSbSsSbSsBsBsSsSbSsBsBsSsSbBsBsSsSsSsBbSsBsSsSbBsSsBsSsSsSbSsBsBsSsSbSbSbSsSsSsSsBbBsBsBsSbSsSsSsSsSsBbBsBsBsSbSsSsSsBsBbSsSsBbSsSsSsBsSbBsSsBsSsSsBsSsBbSsBsSsBsSbSsSbBsSsBsSsBsSsSsSbBsBsSsBsSbSsBsSsSbBsSsSbBsSsBsSsBbSsSsBsSsSsSbSbSbSsBsBsSbSsSsSbBsSsBsSsSsBsBbSsSsSbBsBsSsSsSsSbBsBsSsSbBsSsBsSsSsSbSsBsBsSsSbSbSbSsSsBbSsBsSsSsSsSsBbBsBsSsSbBsSsSbSsSsBsBsSbBsSsBsSsBsSbSsSsBsSsSbSsBsBsSbBsBsSsSsSsBsSbSsBsSsBsSbSsBsSsSbSbSbSsSsBbSsSsB'
    if a =='"What is zinc?" That\'s what you do if you can\'t zwim.':
        return'SsBbSsSsBsBsSsBbSsSsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsBsSsSbBsSbBsSsSsBsSsBbSsBsSsSsBsSsSbBsBsSsSsSbBsSbBsSsSsBsSsBsSbBsSsSsBsSsBbSsSsSsBbBsSsSsBbSsSsBsSsBsSsSbBsSsBsSbSsBsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsSbSsBsBsSsBbSsBsSsSsBsSsSbBsBsSsBbSsSsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsBsSsSbBsBsSsSsBbSsBbSsSsBsSsSbBsBsSsSsSsBsSsSbBsSbSbSsSbSsBbSsSsBsSsSsBsSsSbBsSbBsSsSsBsBsSbSsSsBsSsBsSsSbBsBsSsSsBbSsBbSsSsBsSsSbBsBsSsSsSsBsSsSbBsSsBsSsBbSsSbSbSbSsSsSsBsSbBsSsSsSbSsBsBsSsBsSbSsBsSsBsSsSbBsBsSsSsSbBsBsSsBbSsSsSbBsSsSsBsSbSsSbSbSsSbBsSsBsS'
    if a =='I like watching plays, but mostly I like to actinium.':
        return'BbBsSsSsSsSsBsSbSsBsSbBsSsBsSsBbBsSsSsSsSsSsSbBsBsBsSbBsSsSsSsBsSbSsBsSsBsSsBbSsBsSsSbBsSsSsBbSsSsBsSsSsBsSbBsSsBsBsSbSsBbBsSsSsSsSsSsBbBsSsBsSsBbSsSsSsBsSbSsBsSbSsSsBsBsSbBsSsBsSsBsSsSbBsSsBbSsBsSsSsBsSsBsSbSsSbSbSbSsSsSsBsSbSsBsBsSbSsBsSsSsBsSbBsSsSsBbSsSsBsSsBsSbSsBsSsSsSsBbBsSbSbSsSbSsBsSsBsSbSsSsBbSsSsBsSbBsSsBsSsBbSsBsSsSsSsBsSbSsBsBbBsSsSsSsSsBsSbSsBsSbBsSsBsSsBbBsSsSsSsSsSsSbBsBsBsSbBsSsSsSsBsSbSsBsSsBbSsSsBsSbSbSsSbSsSsBsSbSsBsBsSsSbBsSsSsSsBsSbBsSsBbSsSsBsBbBsSsSsSsSsSsBbBsSsBbBsSsSsSsSsBsSbBsSsSsSsSsBbBsSsBsSsSbB'
    if a =="I've never heard of a weavers' rooms without aluminum.":
        return'BbSsSsBsSsBsBbSsSsSsSsBsSbBsSsBbSsSsSsBsBsSsBsSbSsBsBsSsSbSsBbSsSsSsBsSsBsSbBsSsBbSsSsSsBsSsBsSbSsBsBsSsBsSbSsSsSbBsBsSsBbSsSsSsBsSbBsSsBsSsSsBsSbSsBsBsSsBbSsSsBsSsBsSbSsSbSbSsSbSsSbBsBsSsSsBsSsBsSbSsSbBsSsBsSsBsSsBsSbSsSsSsBsBbSsBbSsSsSsBsSbBsSsBsSsSsBsSbBsSsBbSsSsSsBsSsBsSbSsBsSsBsSsSbBsBsBbSsSsSsBsSsBsSbSsSsBsSbSsBsSbSbSsSbSsSbSbSsSbSsSsBbSsBsSsSsBsSsSbBsBsSsBsSbSsSsSsBsBbSsBbSsSsBsSsSbSsSsBsBsSsSbBsBsSsSbSbSsSbSsBsSsSsSbBsSbSsSsBsBsBsSsBsSbSsSbBsSsBsSsSsSsSbBsBsBsSsSsSbBsSsBbSsBsSsBbSsSsBsSsBsBsSsSbSsBsSsSsSbBsSsBbSsBsSsSbSbSbSsS'
    if a =="The church towers aren't any good since there's nobelium.":
        return'SsBsSsSbBsSsSbBsBsSsSsSsBsBbSsSsBsBbSsSsSsSsSsBbBsSsSbBsBsSsBsBsSsSbSsBsSbSsSsBsSsSsSsBbBsSsSbBsBsSsSsBsBbSsSsSsBsSsSbBsSsSsBsSbBsSbBsSsSsBsSsSsBsBbSsBsSbSsSsBsBsBbSsSsSsSsBsBbSsSsSsBsBsSbSsBsSbSsSsBsSsSsBsBbSsSbBsSsBsSsBsSsBsSbSsSsBsSsSbBsSsBsBbSsSsSsBsBsSbSsSbBsSsBsSsSsBsSsBbSsSsBsBbSsSsSsSsBbSsBsSsSsBsSbBsSsSsBsSbBsBsSsSbBsSsSsBsBbSsSsBsBbSsSsSsBsSsSbSsBsSbBsSsBsSsSsSsSsBbBsSsSsBsBbSsSsBsBbSsSsSsBsSsSbBsSsSbBsBsSsSsSsBsBbSsBsSbSsSsBsSsSsBsBbSsBsSsBsSbSsBsBbSsSsSsSsBsBbSsSsSbBsSsBsSsSsSsBsSbBsSbSsBsBsSsSsSsBsBbSsSbSbSsSbSsBsSsSbSsBsBsBsSsSbSsBsBsSbSsSsSsSsSbBsB'
    if a =='The police caught the robbers after their radon the bank.':
        return'BsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsSsBsSbBsSsBbSsSsBsSsSbBsSsBsSsBsSbSsSsBsSbSbSbSsSsSsSsSsBbBsBsSsBsSbSsSbSbSbSsSsSsSsSbBsBsSbBsBsSsSsBsSsSsSbBsBbBsSsSsSsBsSsSbBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsSsBbSsBsSsBbSsSsBsSsBsSsBbSsSsBsSsBbSsSsSsSsSsBbBsSsBbSsBsSsBsSsSbSsBsBsSsBsSbSsSsSsSbBsBsBsBsSsSbSsBsSsSbBsSsSsSsSsBbBsSsBbSsBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSbSsSsBsSsBbSsBsSsBsSsBsSbSsSsBbSsBsSsSsSsSbBsBsSbBsSsSsBsBbSsSsBsSsSsSsBbBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsBsSsBbSsSsSsSsSbBsBsSsSsBbBsSsSsSbBsSsBsBsBsSbSsS'
    if a =="I didn't have time to read all the books; I just scandium.":
        return'BsBbSsSsSsSsBbBsSsSsSbSbSbSsSsBsBbSsSsSsSbSbSbSsSsSsSbBsBsSsBsBsSsSbSsSbSsBsSsBsSsBbBsSsSsBsSbSsBsSsSsSsBsSbBsSsSsBbBsSsSsSsSsBbBsSsBbBsSsSsSbSsBsSsBsBsBbSsSsSsSbSsSsBsBsSsSsSsBbBsSsBbBsSsSsSbSsBsSsBsSbSsSbSbSsSsBbBsSsSsSsSbSbSbSsSsSsSsBbBsSsSsBsSbBsSbSbSbSsSsSsBbBsSsSsSsSsBsSbBsSsSbBsSsBsSsSbBsSsBsSsBbBsSsSsSbSsBsSsBsBsSbSsBsSsSsSsSsBbBsSsBbBsSsSsSbBsBsSsSsSbSsSbSbSsSbSsSbSbSsSsBbSsBsSsBsSsSsBbSsSsBsSbSsBsSsBbBsSsSsBsBbSsSsSsSsBbBsSsSsBsSbSsSsBsBsSbBsSsSsBsSsSsBbSsSbSsBsSsBsSsBbBsSsSsBsSsSsBbSsBsSsSbBsSsSsSsBsSbBsSsSbBsBsSsSbSbSbSsSsBsBbSsSsSsBsSbBsSsSsSbSsSsBsBsBbSsSsSsB'
    if a =='Only a few of the plants survived, but manganese ever grow.':
        return'BsSsBsSbSsBsSsSsBbSsBsSsSbBsSsSsBsSsSbBsSsSbBsBsSsSbSbSsSbSsSsSbBsBsSsSsBsSsBbSsBbSsSsSsBsSsSsSbBsBsSsSbBsBsSsBsSsBsSbSsSsBsSsBbSsSsSbBsBsSsSsSsBbSsBsSsSbSsBsBsBbSsSsSsBsSsSbBsBsSsBbSsBsSsSsBsSsSbBsSsSbSbSsSbSsBsSsSsBbSsSsSsBbSsBsSsBbBsSsSsSsSbBsBsSsSsBbBsSsSsSsBsBsSbSsSsSsBbBsSsSbBsSsSsBsSbSsSsBsBsSbBsSsSsBsBbSsSsSsBsBsSbBsSsSsSsBsSbBsSsSsSbBsBsSsSsBbSsBsSsSsBsBsSbSsSsSsBbSsBsSsSbBsBsSsSbSbSbSsSsSbSbSsSbSsBsSsSsBbSsSsBsSbSsBsSbSbSsSbSsBsSsSsBbSsBbSsSsSsBsSsBbBsSsSsBbSsSsSsBsSsSbBsBsSsBbSsSsSsBsSbBsSsSsBsBbSsSsSsBsSsSsBbBsSsSsSbBsBsSsSsBsSbSsBsSsSsBbBsSsBsSsBsSbSsSsSsSbBsBsBsBsSsSbS'
    if a =='The rope gave way just as they were chlorine the drawbridge.':
        return'BbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSbSsSsBsBsSsBsSsBbSsBsSbBsSsSsBsSsBsSbSsBbSsSsSsBsSbSsSsBsBsSsBbBsSsSsSsSsBsBbSsSbBsBsSsSsBbSsSsSsBsSbSsSsBsBsSbBsSsBsSsSsSsBsBbSsSsBsSbSsBsSbSsSsBsBsSsBsBbSsSsSsBsSsSbBsBbBsSsSsSsBbSsBsSsSsSbSsSsBsBsSsSsBsBbSsBbBsSsSsSsSbSsSsBsBsBbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSsBsSbSsBsSbSsSsBsBsSbBsSsBsSsBbSsSsSsBsSsBsSsBbSsBbSsSsSsBsSbSsSsBsBsSbSbSsSbSsSsSsBbSsBsBbSsSsBsSsBsSbBsSsSsSsBsSsBbSsBsSsBbSsSsSsSsSbBsBsBbSsSsSsBsSbSsSsBsBsBbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSbSsSsBsBsBsBsSsSbSsSsBsSsBbSsSsSsBsBbSsSbBsSsBsSsBsSsSsBbSsSsBsSsBbSsBsSsBbSsSsBsBsSsSbSsSsBbBsSsSsBbSsSsSsBsSsBsBsSbS'
    if a =="Come down to Dr. Smith's biotech lab and see the oxygen-erated.":
        return'BsSbSsSsBsBbSsSsBsSsSbSbSbSsSsSsSsBsBbSsSbSsSsBsBsSsBbSsBsSsBbSsSsBsSsBbSsSsSsBsSsBsSbSsBsSbSsSsBsBsSbBsSsSsBsBbSsSsBsSsSbSsSsBsBsSsBbSsBsSsBsBsSbSsSsBsSsSsBbSsSbSsSsBsBsSsSbSsBsBsSbSbSbSsSsBbBsSsSsSsSbBsSsSsBsBsSsBbSsSsSbBsBsSsSsSsSbSsBsBsSbSsSsBsBsBbSsBsSsSsBbBsSsSsSsBbSsSsBsSsSbBsSsSsBsSsSsBsBbSsBsSbSsSsBsBsSsBbSsSsSbSsSsBsBsSsBsBbSsSsSsBsSbBsSsBbSsBsSsSsSbSsSsBsBsSsBsSbBsSsSsBsSbSsBsSsBbSsBsSsSbSsSsBsBsSsSbSsBsBsSsSsBsBbSsSsSsBsBbSsSbSsSsBsBsSbBsSsSsBsBsSsBbSsSsSsSsBsBbSsSbSsSsBsBsBbSsSsBsSsSsBsSsSbBsSsSbSbSbSsBsSsSbSsBsSsSsBsBbSsSsBsSbSsBsSbSsBsBsSsSsSsBsBbSsBsBsSbSsSsSsBsSbBsSsSbBsSsSsBsSsSsBsBbSsSsBbSsBsSsBsSsSsBbS'
    if a =='The last batch of cookies you made was great...can I have samarium?':
        return'BsSsSsBbSsSsBsSsBbSsBsSsSbSsBsSbBsBsSsSsBsSsBsSbSsBbSsBsSsSsSbSsSsBsBsBsSsSsBbSsSbBsBsSsSsBsBsSsSbSsBbSsBsSsSsBsSsSsBbSsBsSsBbSsSsSsBsSsBbSsSbBsBsSsSsBsSbSsBsSsBbSsSsSsBsSbBsBsSsSsBsSsBbSsSsBsSbSsBsSsBsSbSsBsSsSbSsSbSbSsBsBsSbSsSsBsSsSbSsBsSbSsSsBsBsSbBsBsSsSsSsSbSbSbSsBsSbSsBsSsSsSbBsSsBsSbBsBsSsSsBsSsSbBsSsBbSsBsSsSsSsBsBbSsSsBsSsSbSsBsSbBsBsSsSsBsSbSsSsBsBbSsBsSsSsSbSsSsBsBsSbBsBsSsSsSsBbBsSsSsSsSsBbBsSsBsSsSbSsBsBbSsBsSsSsBsSsSsBbSsBsSbBsSsSsBsSbBsSsSsBsSbBsSsSsBsSsBbSsSsBbSsBsSsSsSsBsSbBsSsSbBsBsSsSsBsBsSbSsSsSbBsBsSsSsSsBsSsBbSsBbSsBsSsSsSbSbSbSsSsBsSsSbSsBsSbBsBsSsSsSbSsSsBsBsBbSsBsSsSsBsSsSbBsSsBbSsBsSsSsSsSsBbBsSsBsBsSbSsSsSsSbBsSsBsBsSsSbBsSsSsBbSsBsS'
    if a =='We had a roach problem, but called the exterminator to get iridium.':
        return'SsSbSsBsBsSbBsBsSsSsSsBsSsBbSsBsSbSsSsBsBbSsBsSsSsBbSsSsBsSsSsBsSsBbSsBbSsBsSsSsSsBsSsBbSsSsSbBsSsBsBbBsSsSsSsBbSsBsSsSsBsSsSsSbBsBsSbSsSsBsSsBsSsBbSsSsBsBbSsSsSsSbBsSsBsBbBsSsSsSsBsSbBsSsSsSbSsBsBsSsSbBsBsSsSsSsBsSsSbBsSsSbBsBsSsSsBsSsBbSsBsSbBsSsSsSsSsSbBsBsBsSsSbBsSsSsBsSsBbSsBsSsSsSbBsBbSsBsSsSsSbSsBsBsSsSbSsBsBsSsSbBsBsSsSsBbSsSsBsSsSsBsSsBbSsBsSsSbBsSsBsSbSsSsBsSbBsBsSsSsSsBsSsBbSsSbBsBsSsSsBsSsSbSsBsBsSsSbBsSsSbBsBsSsSsSsSbBsSsBsSsBsSsSbBsBsSsSsBbSsSbBsSsBsSsBbSsBsSsSsBsSsSbBsSsBbBsSsSsSsSsSbBsSsBsSsBsSsBbSsBsSsSbBsSsBbBsSsSsSsSsBsSsBbSsSsBbSsSsBsSbBsBsSsSsBsSsSbBsSsSsBsSsBbSsBsSsSsBbSsSsSbBsSsBsBsSsSsBbSsBbSsSsBsSsBsSsSsBbSsSsSsSbBsBsSsBsSsSbBsSsBsSbBsS'
    if a =="I'll never bicycle one hundred miles again, considering how thorium.":
        return'BsSsBbSsSsSsBsSsBbSsBsSsSsSbBsBsSsSsSbBsSbSbSsSbSsSbBsSsSsBsSsBsBbSsSsBsSbSsBsSsSsBsBbSsSsBsBsSbSsSsSbSbSsSbSsSbBsBsSsSsBsSsBbSsSsSsBsSbBsSsBbSsSsBsSsSsBsSbBsSsBsSsSsSbBsSsBsBbSsSsSbSbSsSbSsBsSsBsSbSsSbBsSsSsBsSsBsBbSsSsSbSbSsSbSsSsSsBbBsSsSsSbSsBsBsSbBsSsSsBsSsBsSbSsBsBsBsSbSsSsSsBsBbSsSsSsBsSbSsBsSbSbSsSbSsBsSbBsSsSsBsSsBbSsSsBsSsSsSbBsSsBsBbSsSsBsSsSbBsSsSbSbSsSbSsBsBsSsSbSsSsBsSsSbBsBsBsSsSbSsBsSsBbSsSsSbBsSsSsBsSsSsBsBbSsSbSbSsSbSsSsBsSbBsSsBsSsBsSbSsSbBsSsSsBsBsSsSbBsSsBsSsBbSsSsSsBsSbSsBsSsBsBbSsSsBsBsSbSsSsBsSsBbSsSsSbBsSsSsBsSsBsSsSbBsSbSbSsSbSsSsSsBbBsSsBsSsBsSbSsSsSsBsSbBsSbSbSsSbSsSsBbSsBsSsSsSsBbBsSsBsSsBsSbSsBsBsSbSsSsBsSsBbSsSsSsSbSsBsBsBsSbBsSsSsBsSbSsSsB'
    if a =="I can't wait until he's dead so we can barium in the krypton the hill.":
        return'SsBsSsBbSsSsBbSsSsBsBsBsSsSbSsBsSsSbSsBsBsSsSsSbBsSsBbSsBsSsBsSsSbBsSsSsBbSsSsBsBsSbBsSsSsBsSsSbSsBsSsBsSsBbSsBsSsSbBsSsSsBbSsSsBsSsBsSsSbBsBsSsSsSbBsBsSsSbBsSsSsBsSsBbSsSsSsSbBsBsSsBbSsSsBsBsSsBsSbSsSbSsSbSbSsSsBbSsBsSsSsSsBbBsSsSsBbSsSsBsSsSbBsSsBsSbSsSbSbSsBsSsSbSsBsSsSbBsSsBsSsBbSsSsBsSsSsBbBsSsBbSsBsSsSsSsBbSsSsBsBsSbBsSsSsSbSsSbSbSsSsBbSsSsBsBsBsSsSbSsBsSsSbSsBsBsSsSsSbBsSsBbSsSsBsSsBsSbSsBsBsSsSbSsBsSbBsBsSsSsSsBsSsBbSsSsBsSsSbBsSsSbBsBsSsSsBbSsSsBsSsBsSsBbSsBsSsSsSbBsSsBbSsSsBsBsSsSbBsSsBsSsBsSbSsSbSsSbSbSsSsBbSsSsBsBsSbSsBsSsSbBsBsSsSsSsBbBsSsSsSsSsBsSbBsBsSsSbBsSsBbSsBsSsSsBsSsSsSbBsSsBbSsSsBsBsSsSbBsSsBsSsBsSbSsSbSsSbSbSsSsBbSsSsBsBsSsBsSbSsSsBsSsBbSsSsSsSbBsBsSsSsSbBsBsBbSsSsBsS'
    if a =="It's necessary to galvanize the ship so it won't rust through and zinc.":
        return'BsSbBsSsSsSsSbSsBsBsSsSsBbBsSsSsSbSbSbSsSsBsBbSsSsBbSsSsSsBsSsSsSsBbBsSbSsSsBsBsSsSsSsBbBsSsSbSbSbSsSsSbSbSbSsBbBsSsSsSsSsBsSbSsBsBbSsBsSsSsSsBsBbSsSsSsSbSsBsBsSsBbSsSsBsSsBsBbSsSsBbSsSsBsSsBbBsSsSsSsSbSsBsBsSsBsSsSsBbSsBbBsSsSsSsBbSsSsSsBsBsSbBsSsSsSbSsSbSbSsSsSsSsBbBsSsBsBbSsSsSsSbSsBsBsSbBsBsSsSsSsSsSsBbBsSsBsBbSsSsSsSbSbSbSsSbBsBsSsSsBsSbBsSsSsBsBbSsSsSsSsBsBbSsSsSsSbSbSbSsSsBbSsSsBsSsBsBbSsSsBsSbBsSsSsSsSbSsBsBsSsBsBbSsSsBsSsBsSbSsSsBbSsSsBsBbSsSsSsBsSsSsBbBsSsSsSbSsBsBsSsBsBbSsSsSsBsSbSsBsBsBsSbSsSsSsSbSbSbSsSsSbSsBsBsSsBsBbSsSsSsSbSsBsBsSbBsBsSsSsSsBsSbSsBsSsBbSsSsBsBsBsSbSsSsBbSsSsBsSsSbBsBsSsSsSsBsBbSsSsBbBsSsSsSsBbSsSsSsBsSsSsBsSbBsSsBsBbSsSsSbSsSbSbSsBsSbBsSsSsBbSsSsSsBsSbSsSsBsBsSsSbBsSsB'
    if a =='I bought twelve cookies, but I ate hafnium. Then I ate the other six; now they argon.':
        return'BbSsBsSsSsSsSsBbBsSsBbBsSsSsSsSbSbSsSbSsSsSbBsBsSsSsBbSsBsSsSsBsSsBbSsBsSbSsBsSsSsSsBbBsSsBsSbSsBsSsSbBsSsBsSsSsSbBsSsBsBsSsBsSbSsSsBbSsSsBsSsSbBsSsBsSsSsBbBsSsSbBsBsSsSsSbSbSsSbSsSbSbSsSbSsSbBsSsSsBsBbSsBsSsSsSsSbBsSsBsSsBsSbBsSsBsSsBbSsSsSsSsBbBsSsBbBsSsSsSsSsSbBsBsSsBsSbSsBsSsSsSsBbBsSsBbSsBsSsSsSsSsBbBsSsSbSsBsBsSsBsSbSsBsSsSsSbBsSsBsSsSsBbBsSsSsBsSsBbSsSbSsBsBsSsSsSsSsBbBsSsBsBbSsSsBbSsBsSsSsSsSbBsBsSsBsSsSbBsSsSsSsBbSsBsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsBsBbSsSsSsSsBbBsSsBbSsBsSsSsSsSsBbBsSsSbSsBsBsSsBsSbSsBsSsSsSbBsSsBsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsSsBbBsSsSbSbSsSbSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsBsBsSbSsSsSsSsBbBsSsSsBsSbBsSsBbSsBsSsSsBsSsSsBbSsBbSsSsSsBsSsSsBbBsSsSsBsBbSsSsSbSbSsSbSsSbBsSsBsSsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsBsSbSsBsSsSsBbBsSsSbSsBsBsSsBsBsSbSsSsSsBbSsBsSsSbSbSsSbSsSsBsBbSsSsSsSsBbSsB'
    if a =="Be careful, if your pianos need repairs, that you don't let someone who's in neptunium.":
        return'SsBbBsSsSsBbSsSsBsSsSsSsBbSsBsSbBsBsSsSsSbBsSsBsSsSsSsSbBsBsBbSsSsBsSsSbBsSsSsBsSsBsSbBsSsBsBbSsSsSsSbSsSsBsBsSsSsBbSsBsSbSsBsSsBsSbBsSsSsBsSsSsBbSsBsBsSsSsSbBsBbSsBsSsSsSsBsSbBsSsSsSsSbBsBsSsSsBbSsBsBsSbSsSsBsSbSsBsSsBsSbBsSsBsSsSsBbSsSsBsBbSsBsSsSsBsSsSsBbSsSsSsBbSsBsSsBbSsSsBsBbSsSsBsSsBbSsSsBsSsBsSsSbBsSsSsSsBbSsBsSsSsSbBsBsBbSsSsBsSsBsSbSsSsBsSbBsSsBsSsSbSsBsSsBsSsSsSbBsBsBsSsSsBbSsSbSsSsBsBsSsSsBbSsBsBsBsSsSbSsSbSsBsBsSsSbBsSsBsSsBsBsSsSbSsSsSsBbSsBsBsSsSsSbBsBbSsBsSsSsSsBsSbBsSsSsSsBbSsBsBsSsSbBsSsBbSsBsSsSsSsBbSsSsBsBsSsBbSsSsBsBsSsSbSsSsSsBbSsBsBsBbSsSsSsBbSsSsBsSsBsBsSsSbSsSsSsBbSsBsBsSsSsBbSsBbSsBsSsSsSsSbSbSbSsBbSsSsBsSsBbSsBsSsSsSsBbSsSsBsBbSsSsBsSsSsSsBbSsBsSsSsBsSbBsSbSsBsBsSsBbSsBsSsSsBsSsBbSsSsBsSsSsBbSsSsSsBbSsBsSbSsBsSsBsSsBbSsSsBsSsSsBbSsBsSsBbSsSsBsBbSsSsBsSsBsSbSsSsBsBsBsSsSbSsSsBsSbBsSsSsBbSsSsBsSbSsBsSsBsSsBsSbBsSsSsSbSbSbSsBsSbSsBsS'
    if a =="I'll steal the horses as soon as I can think of a way to get the mendelevium unguarded.":
        return'SbBsSsBsSsSsSbBsBsSsSsSbSbSbSsSsSbSbSbSsSsSsSsBbBsSsSbBsSsBsSsBsBsSbSsSbSsBsBsSsSbSsSbSbSsSsSbSbSbSsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbSsBsBsSsSsSsSsBbBsBsSsBsSbSsSbSbSbSsSsSsSsBbSsBsSsSbBsSsBsSbSsBsBsSsSsSbBsSsBsSsSsSsBbBsSbSsSbSbSsSsSbBsSsBsSsSsSsBbBsSsSbBsSsBsSbSbSbSsSsSbSbSbSsSsSbBsSsSsBsSsSsSsBbBsSbSsSbSbSsSsSbBsSsBsSsSsSsBbBsSbBsSsBsSsSsSsSsBbBsBbSsBsSsSsSbSsSbSbSsSbBsSsSsBsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbBsSsBsSsSbBsSsSsBsSbSsSsBsBsSsSsSsBbBsSbSbSbSsSsSsBbSsBsSsSsSsSsBbBsSbSsSbSbSsSsSsSsBbBsBsSsSsSbBsSbSsSbSbSsBsSsSbBsSsSsSsSsBbBsSsBsBsSbSsSbSbSbSsSsSsSsSsBbBsBsSsSsBbSsSbSsBsBsSsSsBsBsSbSsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbSsBsBsSsSsSsSsBbBsBbSsSsBsSsSbSsBsBsSsSbBsSsSsBsSsBsSbSsBsSbSsBsBsSsSsSbSbSbSsSbSsBsBsSsBsBsSbSsSsSbBsSsBsSsSsBbBsSsSsBbSsSsBsSsSsSsSsBbBsSsBbBsSsSsSbBsSsSsBsBsSsSsBbSsSsBbBsSsSsSbSsSbSbSsSsSsBbSsBsSsBsSbSsBsSbSsBsBsSsSsBsSbSsBsSsBsSsSbB'
    if a =='The kidnapper tried to leave the country, but the the FBI went to the airport to cesium.':
        return'BsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsSbSbSbSsSsSbBsBsSsSbSsBsBsSsBsSsSbSsBsSsBsSbBsSsSsBsBsSbSsSsBsBsSbSsBsBbSsSsSsSsBbBsSsSsSsBsSsBbSsBsSsSsBbSsSsBbBsSsSsSsSbBsBsSsBsBbSsSsSsSbSsBsBsSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsBbSsSsSsBsBsBbSsSsSsSsBsSbBsSsSsBsSbSsBsBsBbSsSsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsSsSsBbBsBsSbSsBsSsBsBsSsSbSsBsSsSbSsBsBsSsSsBbSsSsBbBsSsSsBbBsSsSsSsBsBsSbSsSsSsBsSsBbSsSsSsSbBsBsBsBsSsSbSsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSbBsBsSsSsSsSsSbBsBsSsSbBsBsSsSsBsSsBbSsSsSsBsBbSsBsBbSsSsSsBsSsSbSsBsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsBsSbBsSsSsSbBsBsSsSsBbBsSsSsSsBsBsSbSsBsSbSsBsSsSsBbBsSsSsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsSsSsSsBbBsBsBbSsSsSsBsSbSsSsBsSsSbBsBsSsBsBsSsSbSsSbBsSsSsBsBbSsBsSsS'
    if a =="The hubcaps are missing, the seats are ripped and the doors are dented...where's the carbon?":
        return'SbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsSsBsSbBsBsSsSbSsBsBbSsSsSsBsSsBsBbSsSsSbSbSbSsSsBsBsSsSbSsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsBsSsSsBbSsSsBsSsSbBsBsSsBsSbSsBsSsBsSbSsSsBsSsSbBsBsSbSsSsBsSbSsBsSsBsSsBbBsSsSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsBsSsBsSbSsSsSbBsSsBsSbSbSbSsSsSbBsSsSsBsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsBsSsSsSbBsSsBsSsSbBsBsBsSsSbSsBsBsSsSbSsSsSbBsSsBsSsBsSbBsSsSsSbSbSbSsSbSbSbSsSsBsSbSsSsBsSsBsSbBsSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsBsSbBsSsSsBbSsSsBsSsBbSsSsBsBsSsSsSbBsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsSsBsSbBsSsSsSbBsSsBsBsSbSsSsBsSbBsSsSsBsSsSbBsSsBsSsBsSbBsSsSbSsSbSbSsSbSsSbSbSsSbSsSbSbSsSsBsBsSbSsSsSsBsSbBsSsSbBsSsBsBsSsSsSbBsSsSbBsSsBsBsSbSsBsSsBsSsBsSbSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsBsBbSsSsSbSbSbSsSsBsSsSsSbBsBbSsSsSsBsSsBbSsSsBsBsSbSsSsBsSbSbSsSbS'
    else:
        return'SbBsSsSsBsBsSbSsSsBsSsSbSbSbSsBbSsBsSsSsBsBsSsSbSsBbBsSsSsSsSbSbSbSsSsBsSsSsSbBsBbBsSsSsSsSsBsBsSbSsSbSbSbSsSsBsBsSsSbSsSsBbBsSsSsBsSbSsSsBsSsSbSbSbSsSsSsBsSbBsBsBsSsSbSsSsSsBsSbBsBsSsSsSbBsBsBsSsSbSsSsSsSsBbBsSbSbSbSsSsBsBsSsSbSsBsSsSsBbSsBsSsSsSbBsSsBbBsSsSsSsSsSsBbBsBsSsSsSbBsBbSsBsSsSsBsSsSbBsSsBsSbSsBsSsBsBsSsSbSsSsSsBsSbBsSsSsBbBsSsSbSbSbSsSsBbSsBsSsSsBsBsSsSbSsSsBbBsSsSsBsSbSsSsBsSsSbSbSbSsSsSsBsSbBsBsBsSsSbSsSsSsBsSbBsSbSbSbSsSsBbSsSsBsSsSsSsSsBbBsSbSsBsBsSsSsBsBbSsSsSbBsSsSsBsBsBsSsSbSsBsSsSbBsSsBsSsSsSbBsBsBsSsSbSsSsSsBsSbBsSsSsBbBsSsSbSbSbSsSsBbSsBsSsSsBsBsSsSbSsBsSsSsBbSsBsSbSsSsBsSsSbSbSbSsBsBsSsSbSsSsBsBsSbSsSbSbSbSsSsBsSbSsSsBsBbSsSsBsSsSsSbSbSbSsBsBsSsSbSsSsSsBbBsSsBsSsSsSbBsSsBbBsSsSsBsBsSsSbSsSsSsBsSbBsBsSsSsSbBsBsBsSsSbSsSsSsBbBsSsSbSbSbSsSsBbSsSsBsSsBsSsBsSbSsBsBsSsSbSsBsSsSsBbSsBsSbSsSsBsSsSsBsSbBsSsSsBsSbBsSsBsBsSbSsSbSbSbSsSsBsBsSsSbSsBsSbSsSsBsSsSbSbSbSsBsSsBsSbSsBsBsSsSbSsSsSsBbBsSsBsSsSsSbBsSsBbBsSsSsBsBsSsSbSsSbSbSbSsSsSsBsBbSsSsBbSsSsBsSsBsSsSsSbBsBbBsSsSsSsSbSsBsBsSsSsBsBbSsSsSbBsSsSsBsBsSbSsBsS'
def decode39(sentence, key):
    if sentence == 'SsSbSsBsBsBsSsSsSbBsBsSsBbSsSsSsSsBsSbBsBsSsSsSbBsSsSbBsSsBsBsSbSsBsSsSsSbSbSbSsSsSbSsBsBsSsBsSbBsSsSsSbSbSbSsSbBsSsSsBsSsBsSbBsSsSsBsSbBsSsSbSsBsSsBsSbSbSsSbS':
        return'SULFUR, SO GOOD.'
    if sentence == 'BsSsBsSbSsBsSsSsSbBsBbBsSsSsSsBsSsBsSbSsSbBsSsSsBsBsSsSsSbBsSsSsBbSsBsBsBbSsSsSsBsSsSsSbBsBsSsSbSsBsBsSsSsBbSsBbSsBsSsSsBsSsSbSsBsBsSsSsSbBsSbBsSsSsBsBbBsSsSsSsBsSsSsBbSsBsSsSsSbBsSbBsSsSsBsBsSbBsSsSsSbSsSsBsBsSsSbSbSbSsBsSsSsBbSsBsSbSsSsB':
        return'I HIT MY NEON THE TABLE.'
    if sentence == 'SsSsSbBsBsBsSsBsSbSsBsBsSbSsSsBsBsSbSsSsSsBbSsSsBsSbSsBsSsBsSsSsBsBbSsSsBbSsSsBsSsBsSbSsBsBsSsSbBsSsSsBsSsBbSsBbSsSsBsSsSsSsBsBbSsSsBsSsSbBsSsBsSsBbSsBsSsSbBsSsSsSsSbBsBsBbSsSsBsSsBsSsSbBsSsSsSsSbBsBsSsSsSsBbBsBsSsBsSbSsBsSsSbBsSsSbSsSbSbSsSsSsSbBsBsBbSsSsBsSsSbSsBsSsBsBsSsBsSbSsSbSsSsBsB':
        return'TELLURIUM GOING TO THE STORE.'
    if sentence == 'BbSsSsBsSsBbSsSsSsBsBsBsSsSbSsSsSbBsSsBsBsSsBbSsSsSbSsBsSsBsBsBsSsSbSsSsSbBsSsBsBsBsSbSsSsSbBsSsSsBsBsSsBbSsSsBsSbBsSsSsBsBsSsSbSsSsSsBbSsBsSsBbBsSsSsSsSsBsSbBsSsSsBsBbSsBsSsBbSsSsSbSbSbSsSsBsBsSsSbSsBsSsSsBbSsBsBsSbSsSsSbSbSbSsSsBsSsBbSsSsSsBbSsBsSsBsBsSsSbSsBsSsBbSsSsSsBsSsSbBsSsSbSbSbSsBsBsSsSbSsBbSsSsBsSsSsBsSsSbBsSsSbSbSbSsBsBsSsSbSsSsSsBsSbBsSsSsBbSsBsBbSsSsBsSsSbBsSsSsB':
        return"SLOW DOWN. YOU'RE GOING TO PHOSPHORUS."
    if sentence == 'SbSbSsSbSsSsBbSsSsBsBbBsSsSsSsSsSsSbBsBsBsSsBsSbSsBsSbSsSsBsBbBsSsSsSsBsSsBsSbSsBbBsSsSsSsBsSsSsBbSsSbSbSbSsSsSsBsSbBsSsBsSsSsSbBsBbBsSsSsSsSsBbSsSsBsBsSbBsSsSsSsBbBsSsSsBbSsBsSsSsSbSsSsBsBsBbBsSsSsSsSsSbBsSsBsBsSsBbSsSsSsBbSsSsBsBbBsSsSsSsSsBbSsSsBsSbSsSbSbSsSsBbBsSsSsBbBsSsSsSsSbSsSbSbSsSbSbSsSbSsBbSsBsSsSsSsBbBsSsSsBsSbBsSsSsBsSbSsSsBsBbBsSsSsSsSsSbBsSsBsSbSbSbSsSsBsSbBsSsSsSbSbSbSsSsSsBsSbBsSsBsBsSbSsS':
        return'IT WAS A LONG TREK, BUT THE HIKERS BORON.'
    if sentence == 'SbSsBsSsBsBsSsBsSbSsSsSbBsBsSsBbSsSsBsSsSsBsBbSsSsBsSbSsBsSsSsBbSsSsBsSsSbBsBsSsSsSbSsBsBsSsBsBbSsSsBsSbSsSsBsBbSsSsBsSsSsSbBsBsSsSsSsBsSbBsSbSsBsSsBsBsBsSsSbSsSsBsBbSsSsSsSbSsBsBsSsSsBsSbBsSbSsBsSsBsSsBsBbSsSsSbSsBsBsSsBsSsBsSbSsSsBbSsSsBsSbSbSbSsSsSsSsSbBsBsBsSsSbSsBsBsSsBbSsSsSbSsBsSsBsSsBsBbSsSsSsSbSsBsBsSsSsBsSbBsSbSsBsSsBsSsBsBbSsSsSsBsBsSbSsBsSsSbSsBsSsSbSsBsBsSsSsSsBbBsSsSsBsSbBsSbSsBsSsBsBsSsBbSsSsSbSsSbSbS':
        return'ELSA JUST WASHED THE FLUORINE THE KITCHEN.'
    if sentence == 'SsBsSsBbSsSsSbSsBsBsBsBbSsSsSsSsBbSsSsBsSsBsSbBsSsSsBsSbSsBsSbSsBsBsSsSsSbSsBsBsSsBsSbBsSsSsBsBbSsSsBbSsSsBsSsSsSbSsBsBsBsBsSsSbSsBsSbBsSsSsSbBsSsBsSsSsBsSbBsSsSsSbSsBsBsSbSsBsBsSsSsBsSbBsSsSsSbSsBsBsSsSbBsSsBsBsSbBsSsSsSbSsBsBsSsBbSsSsSsBsSsBsSbBsSsBbSsSsBsSsSsBsSbBsSsSsSbSsBsBsSbBsSsBsSsSsBsBbSsSsSsBbBsSsSsSbBsSsBsSsBsSbBsSsSsSsBsSbBsSsSsSbSsBsBsBbSsSsBsSsSsBsSbSsBsSsSbSsBsBsBbSsSsBsSsSbBsBsSsSsBsBsSsSbSsSsBsBbSsSsSsSsSsBbB':
        return"IT'S NOT MATURE TO THROW A TEMPER TANTALUM."
    if sentence == 'BbSsSsBsSsSbSbSsSbSsSsBbSsSsBsSsBbSsBsSsSsBsSbSsBsBbSsBsSsSsSsSbSbSbSsBsSbBsSsSsBsSsBsSbSsBbSsBsSsSsSbSbSbSsSsSsBbSsSsBsSsSsBsSbBsSsSbSbSbSsSsSsSbBsBsSbSbSsSbSsBsSsBsSbSsSbBsSsSsBsBbSsBsSsSsSsBsBsSbSsSsBsSsSbBsBsSsBsSbSsSbSbSsSbSsBbSsBsSsSsBsSbBsSsSsBsSsBsSbSsSbSbSsSbSsBsSsBsSbSsBbSsBsSsSsSbSsSsBsBsSsBbSsBsSsSsBsSbBsSsBbSsBsSsSsBsSbSsBsSsBsSsBsSbSsSsSbSbSbSsBbSsBsSsSsSsSsBsSbBsSbSsSsBsBsBsSbSsBsSsSsSsBsSbBsSsBbSsSsBsSsSsSbBsBsSsSsBbBsSsSbBsBsSsS':
        return'BRING THE PICTURES OVER HERE AND LET CALCIUM.'
    if sentence == 'SbSsBsSsBsBsSsSsSbBsSsSbSbSbSsBbSsSsBsSsBbSsSsSsBsSsSsSbBsBsBbSsBsSsSsBsSsSsSbBsBsSbSsBsSsSsSbSbSbSsBbSsBsSsSsSbBsSsBsSsSsSbSbSbSsBbBsSsSsSsSsSsSsBbBsSsBsSbSsBsSsSbSbSbSsSsSsBbBsSsSsBsSbSsBsSsSbSbSbSsBsSsBbSsSsBsSbSsBsSsSsBsSsBbSsSbSbSsSbSsSsSbSbSbSsBbBsSsSsSsSsSsSsBbBsBbSsBsSsSsSsSbSbSbSsSsBbBsSsSsSsSbSbSbSsBbSsSsSsBsBsSbSsSsBsSsSsBbSsBsBsSsSsSbBsBbSsSsSsBsBsSbSsBsSsSsBsSbSsBsSsSbSbSbSsSsBsSsBbSsSbBsSsBsSsBsSbSsBsSsSsBbBsSsSsSsSsSsBbBsSsSsBbBsSsBsSsBsSbS':
        return'HE WANTED TO BUY MY CDS, BUT I ALREADY SODIUM.'
    if sentence == 'SsSsSsBbBsSsSbBsBsSsBsBbSsSsSsSsBsSsBbSsSbBsSsBsSsSsBsSsBbSsSsSbBsBsSsBsSsBsSbSsSbSsBsBsSsSbSsBsBsSsSbBsBsSsSsSsBbSsBsSsSbBsSsBsSsSsSbSsBsBsSsSbSbSbSsSsSsSsBbBsBsBsSbSsSsSsSsSsBbBsBsBsSbSsSsSsBsBbSsSsBbSsSsSsBsSbBsSsBsSsSsBsSsBbSsBsSsBsSbSsSbBsSsBsSsBsSsSsSbBsBsSsBsSbSsBsSsSbBsSsSbBsSsBsSsBbSsSsBsSsSsSbSbSbSsBsBsSbSsSsSbBsSsBsSsSsBsBbSsSsSbBsBsSsSsSsSbBsBsSsSbBsSsBsSsSsSbSsBsBsSsSbSbSbSsSsBbSsBsSsSsSsSsBbBsBsSsSbBsSsSbSsSsBsBsSbBsSsBsSsBsSbSsSsBsSsSbSsBsBsSbBsBsSsSsSsBsSbSsBsSsBsSbSsBsSsSbSbSbSsSsBbSsSsB':
        return"IT'S STOPPED RAINING, SO YOU CAN GET RADIUM BRELLA."
    if sentence == 'SsBbSsSsBsBsSsBbSsSsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsBsSsSbBsSbBsSsSsBsSsBbSsBsSsSsBsSsSbBsBsSsSsSbBsSbBsSsSsBsSsBsSbBsSsSsBsSsBbSsSsSsBbBsSsSsBbSsSsBsSsBsSsSbBsSsBsSbSsBsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsSbSsBsBsSsBbSsBsSsSsBsSsSbBsBsSsBbSsSsSsSsBsSbBsSbSbSbSsSsSsBsSbSsBsSsBsSsSbBsBsSsSsBbSsBbSsSsBsSsSbBsBsSsSsSsBsSsSbBsSbSbSsSbSsBbSsSsBsSsSsBsSsSbBsSbBsSsSsBsBsSbSsSsBsSsBsSsSbBsBsSsSsBbSsBbSsSsBsSsSbBsBsSsSsSsBsSsSbBsSsBsSsBbSsSbSbSbSsSsSsBsSbBsSsSsSbSsBsBsSsBsSbSsBsSsBsSsSbBsBsSsSsSbBsBsSsBbSsSsSbBsSsSsBsSbSsSbSbSsSbBsSsBsS':
        return'"WHAT IS ZINC?" THAT\'S WHAT YOU DO IF YOU CAN\'T ZWIM.'
    if sentence == 'BbBsSsSsSsSsBsSbSsBsSbBsSsBsSsBbBsSsSsSsSsSsSbBsBsBsSbBsSsSsSsBsSbSsBsSsBsSsBbSsBsSsSbBsSsSsBbSsSsBsSsSsBsSbBsSsBsBsSbSsBbBsSsSsSsSsSsBbBsSsBsSsBbSsSsSsBsSbSsBsSbSsSsBsBsSbBsSsBsSsBsSsSbBsSsBbSsBsSsSsBsSsBsSbSsSbSbSbSsSsSsBsSbSsBsBsSbSsBsSsSsBsSbBsSsSsBbSsSsBsSsBsSbSsBsSsSsSsBbBsSbSbSsSbSsBsSsBsSbSsSsBbSsSsBsSbBsSsBsSsBbSsBsSsSsSsBsSbSsBsBbBsSsSsSsSsBsSbSsBsSbBsSsBsSsBbBsSsSsSsSsSsSbBsBsBsSbBsSsSsSsBsSbSsBsSsBbSsSsBsSbSbSsSbSsSsBsSbSsBsBsSsSbBsSsSsSsBsSbBsSsBbSsSsBsBbBsSsSsSsSsSsBbBsSsBbBsSsSsSsSsBsSbBsSsSsSsSsBbBsSsBsSsSbB':
        return'I LIKE WATCHING PLAYS, BUT MOSTLY I LIKE TO ACTINIUM.'
    if sentence == 'BbSsSsBsSsBsBbSsSsSsSsBsSbBsSsBbSsSsSsBsBsSsBsSbSsBsBsSsSbSsBbSsSsSsBsSsBsSbBsSsBbSsSsSsBsSsBsSbSsBsBsSsBsSbSsSsSbBsBsSsBbSsSsSsBsSbBsSsBsSsSsBsSbSsBsBsSsBbSsSsBsSsBsSbSsSbSbSsSbSsSbBsBsSsSsBsSsBsSbSsSbBsSsBsSsBsSsBsSbSsSsSsBsBbSsBbSsSsSsBsSbBsSsBsSsSsBsSbBsSsBbSsSsSsBsSsBsSbSsBsSsBsSsSbBsBsBbSsSsSsBsSsBsSbSsSsBsSbSsBsSbSbSsSbSsSbSbSsSbSsSsBbSsBsSsSsBsSsSbBsBsSsBsSbSsSsSsBsBbSsBbSsSsBsSsSbSsSsBsBsSsSbBsBsSsSbSbSsSbSsBsSsSsSbBsSbSsSsBsBsBsSsBsSbSsSbBsSsBsSsSsSsSbBsBsBsSsSsSbBsSsBbSsBsSsBbSsSsBsSsBsBsSsSbSsBsSsSsSbBsSsBbSsBsSsSbSbSbSsS':
        return"I'VE NEVER HEARD OF A WEAVERS' ROOMS WITHOUT ALUMINUM."
    if sentence == 'SsBsSsSbBsSsSbBsBsSsSsSsBsBbSsSsBsBbSsSsSsSsSsBbBsSsSbBsBsSsBsBsSsSbSsBsSbSsSsBsSsSsSsBbBsSsSbBsBsSsSsBsBbSsSsSsBsSsSbBsSsSsBsSbBsSbBsSsSsBsSsSsBsBbSsBsSbSsSsBsBsBbSsSsSsSsBsBbSsSsSsBsBsSbSsBsSbSsSsBsSsSsBsBbSsSbBsSsBsSsBsSsBsSbSsSsBsSsSbBsSsBsBbSsSsSsBsBsSbSsSbBsSsBsSsSsBsSsBbSsSsBsBbSsSsSsSsBbSsBsSsSsBsSbBsSsSsBsSbBsBsSsSbBsSsSsBsBbSsSsBsBbSsSsSsBsSsSbSsBsSbBsSsBsSsSsSsSsBbBsSsSsBsBbSsSsBsBbSsSsSsBsSsSbBsSsSbBsBsSsSsSsBsBbSsBsSbSsSsBsSsSsBsBbSsBsSsBsSbSsBsBbSsSsSsSsBsBbSsSsSbBsSsBsSsSsSsBsSbBsSbSsBsBsSsSsSsBsBbSsSbSbSsSbSsBsSsSbSsBsBsBsSsSbSsBsBsSbSsSsSsSsSbBsB':
        return"THE CHURCH TOWERS AREN'T ANY GOOD SINCE THERE'S NOBELIUM."
    if sentence == 'BsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsSsBsSbBsSsBbSsSsBsSsSbBsSsBsSsBsSbSsSsBsSbSbSbSsSsSsSsSsBbBsBsSsBsSbSsSbSbSbSsSsSsSsSbBsBsSbBsBsSsSsBsSsSsSbBsBbBsSsSsSsBsSsSbBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsSsBbSsBsSsBbSsSsBsSsBsSsBbSsSsBsSsBbSsSsSsSsSsBbBsSsBbSsBsSsBsSsSbSsBsBsSsBsSbSsSsSsSbBsBsBsBsSsSbSsBsSsSbBsSsSsSsSsBbBsSsBbSsBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSbSsSsBsSsBbSsBsSsBsSsBsSbSsSsBbSsBsSsSsSsSbBsBsSbBsSsSsBsBbSsSsBsSsSsSsBbBsSsBsSsBsSbSsBsSsSbBsSsBbBsSsSsSsSsSsSsBbBsBsSsBsSbSsBsSsBbSsSsSsSsSbBsBsSsSsBbBsSsSsSbBsSsBsBsBsSbSsS':
        return'THE POLICE CAUGHT THE ROBBERS AFTER THEIR RADON THE BANK.'
    if sentence == 'BsBbSsSsSsSsBbBsSsSsSbSbSbSsSsBsBbSsSsSsSbSbSbSsSsSsSbBsBsSsBsBsSsSbSsSbSsBsSsBsSsBbBsSsSsBsSbSsBsSsSsSsBsSbBsSsSsBbBsSsSsSsSsBbBsSsBbBsSsSsSbSsBsSsBsBsBbSsSsSsSbSsSsBsBsSsSsSsBbBsSsBbBsSsSsSbSsBsSsBsSbSsSbSbSsSsBbBsSsSsSsSbSbSbSsSsSsSsBbBsSsSsBsSbBsSbSbSbSsSsSsBbBsSsSsSsSsBsSbBsSsSbBsSsBsSsSbBsSsBsSsBbBsSsSsSbSsBsSsBsBsSbSsBsSsSsSsSsBbBsSsBbBsSsSsSbBsBsSsSsSbSsSbSbSsSbSsSbSbSsSsBbSsBsSsBsSsSsBbSsSsBsSbSsBsSsBbBsSsSsBsBbSsSsSsSsBbBsSsSsBsSbSsSsBsBsSbBsSsSsBsSsSsBbSsSbSsBsSsBsSsBbBsSsSsBsSsSsBbSsBsSsSbBsSsSsSsBsSbBsSsSbBsBsSsSbSbSbSsSsBsBbSsSsSsBsSbBsSsSsSbSsSsBsBsBbSsSsSsB':
        return"I DIDN'T HAVE TIME TO READ ALL THE BOOKS; I JUST SCANDIUM."
    if sentence == 'BsSsBsSbSsBsSsSsBbSsBsSsSbBsSsSsBsSsSbBsSsSbBsBsSsSbSbSsSbSsSsSbBsBsSsSsBsSsBbSsBbSsSsSsBsSsSsSbBsBsSsSbBsBsSsBsSsBsSbSsSsBsSsBbSsSsSbBsBsSsSsSsBbSsBsSsSbSsBsBsBbSsSsSsBsSsSbBsBsSsBbSsBsSsSsBsSsSbBsSsSbSbSsSbSsBsSsSsBbSsSsSsBbSsBsSsBbBsSsSsSsSbBsBsSsSsBbBsSsSsSsBsBsSbSsSsSsBbBsSsSbBsSsSsBsSbSsSsBsBsSbBsSsSsBsBbSsSsSsBsBsSbBsSsSsSsBsSbBsSsSsSbBsBsSsSsBbSsBsSsSsBsBsSbSsSsSsBbSsBsSsSbBsBsSsSbSbSbSsSsSbSbSsSbSsBsSsSsBbSsSsBsSbSsBsSbSbSsSbSsBsSsSsBbSsBbSsSsSsBsSsBbBsSsSsBbSsSsSsBsSsSbBsBsSsBbSsSsSsBsSbBsSsSsBsBbSsSsSsBsSsSsBbBsSsSsSbBsBsSsSsBsSbSsBsSsSsBbBsSsBsSsBsSbSsSsSsSbBsBsBsBsSsSbS':
        return'ONLY A FEW OF THE PLANTS SURVIVED, BUT MANGANESE EVER GROW.'
    if sentence == 'BbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSbSsSsBsBsSsBsSsBbSsBsSbBsSsSsBsSsBsSbSsBbSsSsSsBsSbSsSsBsBsSsBbBsSsSsSsSsBsBbSsSbBsBsSsSsBbSsSsSsBsSbSsSsBsBsSbBsSsBsSsSsSsBsBbSsSsBsSbSsBsSbSsSsBsBsSsBsBbSsSsSsBsSsSbBsBbBsSsSsSsBbSsBsSsSsSbSsSsBsBsSsSsBsBbSsBbBsSsSsSsSbSsSsBsBsBbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSsBsSbSsBsSbSsSsBsBsSbBsSsBsSsBbSsSsSsBsSsBsSsBbSsBbSsSsSsBsSbSsSsBsBsSbSbSsSbSsSsSsBbSsBsBbSsSsBsSsBsSbBsSsSsSsBsSsBbSsBsSsBbSsSsSsSsSbBsBsBbSsSsSsBsSbSsSsBsBsBbSsBsSsSsSsSsBbSsBsBbSsSsSsBsSbSsSsBsBsBsBsSsSbSsSsBsSsBbSsSsSsBsBbSsSbBsSsBsSsBsSsSsBbSsSsBsSsBbSsBsSsBbSsSsBsBsSsSbSsSsBbBsSsSsBbSsSsSsBsSsBsBsSbS':
        return'THE ROPE GAVE WAY JUST AS THEY WERE CHLORINE THE DRAWBRIDGE.'
    if sentence == 'BsSbSsSsBsBbSsSsBsSsSbSbSbSsSsSsSsBsBbSsSbSsSsBsBsSsBbSsBsSsBbSsSsBsSsBbSsSsSsBsSsBsSbSsBsSbSsSsBsBsSbBsSsSsBsBbSsSsBsSsSbSsSsBsBsSsBbSsBsSsBsBsSbSsSsBsSsSsBbSsSbSsSsBsBsSsSbSsBsBsSbSbSbSsSsBbBsSsSsSsSbBsSsSsBsBsSsBbSsSsSbBsBsSsSsSsSbSsBsBsSbSsSsBsBsBbSsBsSsSsBbBsSsSsSsBbSsSsBsSsSbBsSsSsBsSsSsBsBbSsBsSbSsSsBsBsSsBbSsSsSbSsSsBsBsSsBsBbSsSsSsBsSbBsSsBbSsBsSsSsSbSsSsBsBsSsBsSbBsSsSsBsSbSsBsSsBbSsBsSsSbSsSsBsBsSsSbSsBsBsSsSsBsBbSsSsSsBsBbSsSbSsSsBsBsSbBsSsSsBsBsSsBbSsSsSsSsBsBbSsSbSsSsBsBsBbSsSsBsSsSsBsSsSbBsSsSbSbSbSsBsSsSbSsBsSsSsBsBbSsSsBsSbSsBsSbSsBsBsSsSsSsBsBbSsBsBsSbSsSsSsBsSbBsSsSbBsSsSsBsSsSsBsBbSsSsBbSsBsSsBsSsSsBbS':
        return"COME DOWN TO DR. SMITH'S BIOTECH LAB AND SEE THE OXYGEN-ERATED."
    if sentence == 'BsSsSsBbSsSsBsSsBbSsBsSsSbSsBsSbBsBsSsSsBsSsBsSbSsBbSsBsSsSsSbSsSsBsBsBsSsSsBbSsSbBsBsSsSsBsBsSsSbSsBbSsBsSsSsBsSsSsBbSsBsSsBbSsSsSsBsSsBbSsSbBsBsSsSsBsSbSsBsSsBbSsSsSsBsSbBsBsSsSsBsSsBbSsSsBsSbSsBsSsBsSbSsBsSsSbSsSbSbSsBsBsSbSsSsBsSsSbSsBsSbSsSsBsBsSbBsBsSsSsSsSbSbSbSsBsSbSsBsSsSsSbBsSsBsSbBsBsSsSsBsSsSbBsSsBbSsBsSsSsSsBsBbSsSsBsSsSbSsBsSbBsBsSsSsBsSbSsSsBsBbSsBsSsSsSbSsSsBsBsSbBsBsSsSsSsBbBsSsSsSsSsBbBsSsBsSsSbSsBsBbSsBsSsSsBsSsSsBbSsBsSbBsSsSsBsSbBsSsSsBsSbBsSsSsBsSsBbSsSsBbSsBsSsSsSsBsSbBsSsSbBsBsSsSsBsBsSbSsSsSbBsBsSsSsSsBsSsBbSsBbSsBsSsSsSbSbSbSsSsBsSsSbSsBsSbBsBsSsSsSbSsSsBsBsBbSsBsSsSsBsSsSbBsSsBbSsBsSsSsSsSsBbBsSsBsBsSbSsSsSsSbBsSsBsBsSsSbBsSsSsBbSsBsS':
        return'THE LAST BATCH OF COOKIES YOU MADE WAS GREAT...CAN I HAVE SAMARIUM?'
    if sentence == 'SsSbSsBsBsSbBsBsSsSsSsBsSsBbSsBsSbSsSsBsBbSsBsSsSsBbSsSsBsSsSsBsSsBbSsBbSsBsSsSsSsBsSsBbSsSsSbBsSsBsBbBsSsSsSsBbSsBsSsSsBsSsSsSbBsBsSbSsSsBsSsBsSsBbSsSsBsBbSsSsSsSbBsSsBsBbBsSsSsSsBsSbBsSsSsSbSsBsBsSsSbBsBsSsSsSsBsSsSbBsSsSbBsBsSsSsBsSsBbSsBsSbBsSsSsSsSsSbBsBsBsSsSbBsSsSsBsSsBbSsBsSsSsSbBsBbSsBsSsSsSbSsBsBsSsSbSsBsBsSsSbBsBsSsSsBbSsSsBsSsSsBsSsBbSsBsSsSbBsSsBsSbSsSsBsSbBsBsSsSsSsBsSsBbSsSbBsBsSsSsBsSsSbSsBsBsSsSbBsSsSbBsBsSsSsSsSbBsSsBsSsBsSsSbBsBsSsSsBbSsSbBsSsBsSsBbSsBsSsSsBsSsSbBsSsBbBsSsSsSsSsSbBsSsBsSsBsSsBbSsBsSsSbBsSsBbBsSsSsSsSsBsSsBbSsSsBbSsSsBsSbBsBsSsSsBsSsSbBsSsSsBsSsBbSsBsSsSsBbSsSsSbBsSsBsBsSsSsBbSsBbSsSsBsSsBsSsSsBbSsSsSsSbBsBsSsBsSsSbBsSsBsSbBsS':
        return'WE HAD A ROACH PROBLEM, BUT CALLED THE EXTERMINATOR TO GET IRIDIUM.'
    if sentence == 'BsSsBbSsSsSsBsSsBbSsBsSsSsSbBsBsSsSsSbBsSbSbSsSbSsSbBsSsSsBsSsBsBbSsSsBsSbSsBsSsSsBsBbSsSsBsBsSbSsSsSbSbSsSbSsSbBsBsSsSsBsSsBbSsSsSsBsSbBsSsBbSsSsBsSsSsBsSbBsSsBsSsSsSbBsSsBsBbSsSsSbSbSsSbSsBsSsBsSbSsSbBsSsSsBsSsBsBbSsSsSbSbSsSbSsSsSsBbBsSsSsSbSsBsBsSbBsSsSsBsSsBsSbSsBsBsBsSbSsSsSsBsBbSsSsSsBsSbSsBsSbSbSsSbSsBsSbBsSsSsBsSsBbSsSsBsSsSsSbBsSsBsBbSsSsBsSsSbBsSsSbSbSsSbSsBsBsSsSbSsSsBsSsSbBsBsBsSsSbSsBsSsBbSsSsSbBsSsSsBsSsSsBsBbSsSbSbSsSbSsSsBsSbBsSsBsSsBsSbSsSbBsSsSsBsBsSsSbBsSsBsSsBbSsSsSsBsSbSsBsSsBsBbSsSsBsBsSbSsSsBsSsBbSsSsSbBsSsSsBsSsBsSsSbBsSbSbSsSbSsSsSsBbBsSsBsSsBsSbSsSsSsBsSbBsSbSbSsSbSsSsBbSsBsSsSsSsBbBsSsBsSsBsSbSsBsBsSbSsSsBsSsBbSsSsSsSbSsBsBsBsSbBsSsSsBsSbSsSsB':
        return"I'LL NEVER BICYCLE ONE HUNDRED MILES AGAIN, CONSIDERING HOW THORIUM."
    if sentence == 'SsBsSsBbSsSsBbSsSsBsBsBsSsSbSsBsSsSbSsBsBsSsSsSbBsSsBbSsBsSsBsSsSbBsSsSsBbSsSsBsBsSbBsSsSsBsSsSbSsBsSsBsSsBbSsBsSsSbBsSsSsBbSsSsBsSsBsSsSbBsBsSsSsSbBsBsSsSbBsSsSsBsSsBbSsSsSsSbBsBsSsBbSsSsBsBsSsBsSbSsSbSsSbSbSsSsBbSsBsSsSsSsBbBsSsSsBbSsSsBsSsSbBsSsBsSbSsSbSbSsBsSsSbSsBsSsSbBsSsBsSsBbSsSsBsSsSsBbBsSsBbSsBsSsSsSsBbSsSsBsBsSbBsSsSsSbSsSbSbSsSsBbSsSsBsBsBsSsSbSsBsSsSbSsBsBsSsSsSbBsSsBbSsSsBsSsBsSbSsBsBsSsSbSsBsSbBsBsSsSsSsBsSsBbSsSsBsSsSbBsSsSbBsBsSsSsBbSsSsBsSsBsSsBbSsBsSsSsSbBsSsBbSsSsBsBsSsSbBsSsBsSsBsSbSsSbSsSbSbSsSsBbSsSsBsBsSbSsBsSsSbBsBsSsSsSsBbBsSsSsSsSsBsSbBsBsSsSbBsSsBbSsBsSsSsBsSsSsSbBsSsBbSsSsBsBsSsSbBsSsBsSsBsSbSsSbSsSbSbSsSsBbSsSsBsBsSsBsSbSsSsBsSsBbSsSsSsSbBsBsSsSsSbBsBsBbSsSsBsS':
        return"I CAN'T WAIT UNTIL HE'S DEAD SO WE CAN BARIUM IN THE KRYPTON THE HILL."
    if sentence == 'BsSbBsSsSsSsSbSsBsBsSsSsBbBsSsSsSbSbSbSsSsBsBbSsSsBbSsSsSsBsSsSsSsBbBsSbSsSsBsBsSsSsSsBbBsSsSbSbSbSsSsSbSbSbSsBbBsSsSsSsSsBsSbSsBsBbSsBsSsSsSsBsBbSsSsSsSbSsBsBsSsBbSsSsBsSsBsBbSsSsBbSsSsBsSsBbBsSsSsSsSbSsBsBsSsBsSsSsBbSsBbBsSsSsSsBbSsSsSsBsBsSbBsSsSsSbSsSbSbSsSsSsSsBbBsSsBsBbSsSsSsSbSsBsBsSbBsBsSsSsSsSsSsBbBsSsBsBbSsSsSsSbSbSbSsSbBsBsSsSsBsSbBsSsSsBsBbSsSsSsSsBsBbSsSsSsSbSbSbSsSsBbSsSsBsSsBsBbSsSsBsSbBsSsSsSsSbSsBsBsSsBsBbSsSsBsSsBsSbSsSsBbSsSsBsBbSsSsSsBsSsSsBbBsSsSsSbSsBsBsSsBsBbSsSsSsBsSbSsBsBsBsSbSsSsSsSbSbSbSsSsSbSsBsBsSsBsBbSsSsSsSbSsBsBsSbBsBsSsSsSsBsSbSsBsSsBbSsSsBsBsBsSbSsSsBbSsSsBsSsSbBsBsSsSsSsBsBbSsSsBbBsSsSsSsBbSsSsSsBsSsSsBsSbBsSsBsBbSsSsSbSsSbSbSsBsSbBsSsSsBbSsSsSsBsSbSsSsBsBsSsSbBsSsB':
        return"IT'S NECESSARY TO GALVANIZE THE SHIP SO IT WON'T RUST THROUGH AND ZINC."
    if sentence == 'BbSsBsSsSsSsSsBbBsSsBbBsSsSsSsSbSbSsSbSsSsSbBsBsSsSsBbSsBsSsSsBsSsBbSsBsSbSsBsSsSsSsBbBsSsBsSbSsBsSsSbBsSsBsSsSsSbBsSsBsBsSsBsSbSsSsBbSsSsBsSsSbBsSsBsSsSsBbBsSsSbBsBsSsSsSbSbSsSbSsSbSbSsSbSsSbBsSsSsBsBbSsBsSsSsSsSbBsSsBsSsBsSbBsSsBsSsBbSsSsSsSsBbBsSsBbBsSsSsSsSsSbBsBsSsBsSbSsBsSsSsSsBbBsSsBbSsBsSsSsSsSsBbBsSsSbSsBsBsSsBsSbSsBsSsSsSbBsSsBsSsSsBbBsSsSsBsSsBbSsSbSsBsBsSsSsSsSsBbBsSsBsBbSsSsBbSsBsSsSsSsSbBsBsSsBsSsSbBsSsSsSsBbSsBsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsBsBbSsSsSsSsBbBsSsBbSsBsSsSsSsSsBbBsSsSbSsBsBsSsBsSbSsBsSsSsSbBsSsBsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsSsBbBsSsSbSbSsSbSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsBsBsSbSsSsSsSsBbBsSsSsBsSbBsSsBbSsBsSsSsBsSsSsBbSsBbSsSsSsBsSsSsBbBsSsSsBsBbSsSsSbSbSsSbSsSbBsSsBsSsSsSsBbBsSsBsSbSsBsSsSsBsSsBbSsSsSbBsSsBsSsBsSbSsBsSsSsBbBsSsSbSsBsBsSsBsBsSbSsSsSsBbSsBsSsSbSbSsSbSsSsBsBbSsSsSsSsBbSsB':
        return'I BOUGHT TWELVE COOKIES, BUT I ATE HAFNIUM. THEN I ATE THE OTHER SIX; NOW THEY ARGON.'
    if sentence == 'SsBbBsSsSsBbSsSsBsSsSsSsBbSsBsSbBsBsSsSsSbBsSsBsSsSsSsSbBsBsBbSsSsBsSsSbBsSsSsBsSsBsSbBsSsBsBbSsSsSsSbSsSsBsBsSsSsBbSsBsSbSsBsSsBsSbBsSsSsBsSsSsBbSsBsBsSsSsSbBsBbSsBsSsSsSsBsSbBsSsSsSsSbBsBsSsSsBbSsBsBsSbSsSsBsSbSsBsSsBsSbBsSsBsSsSsBbSsSsBsBbSsBsSsSsBsSsSsBbSsSsSsBbSsBsSsBbSsSsBsBbSsSsBsSsBbSsSsBsSsBsSsSbBsSsSsSsBbSsBsSsSsSbBsBsBbSsSsBsSsBsSbSsSsBsSbBsSsBsSsSbSsBsSsBsSsSsSbBsBsBsSsSsBbSsSbSsSsBsBsSsSsBbSsBsBsBsSsSbSsSbSsBsBsSsSbBsSsBsSsBsBsSsSbSsSsSsBbSsBsBsSsSsSbBsBbSsBsSsSsSsBsSbBsSsSsSsBbSsBsBsSsSbBsSsBbSsBsSsSsSsBbSsSsBsBsSsBbSsSsBsBsSsSbSsSsSsBbSsBsBsBbSsSsSsBbSsSsBsSsBsBsSsSbSsSsSsBbSsBsBsSsSsBbSsBbSsBsSsSsSsSbSbSbSsBbSsSsBsSsBbSsBsSsSsSsBbSsSsBsBbSsSsBsSsSsSsBbSsBsSsSsBsSbBsSbSsBsBsSsBbSsBsSsSsBsSsBbSsSsBsSsSsBbSsSsSsBbSsBsSbSsBsSsBsSsBbSsSsBsSsSsBbSsBsSsBbSsSsBsBbSsSsBsSsBsSbSsSsBsBsBsSsSbSsSsBsSbBsSsSsBbSsSsBsSbSsBsSsBsSsBsSbBsSsSsSbSbSbSsBsSbSsBsS':
        return"BE CAREFUL, IF YOUR PIANOS NEED REPAIRS, THAT YOU DON'T LET SOMEONE WHO'S IN NEPTUNIUM."
    if sentence == 'SbBsSsBsSsSsSbBsBsSsSsSbSbSbSsSsSbSbSbSsSsSsSsBbBsSsSbBsSsBsSsBsBsSbSsSbSsBsBsSsSbSsSbSbSsSsSbSbSbSsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbSsBsBsSsSsSsSsBbBsBsSsBsSbSsSbSbSbSsSsSsSsBbSsBsSsSbBsSsBsSbSsBsBsSsSsSbBsSsBsSsSsSsBbBsSbSsSbSbSsSsSbBsSsBsSsSsSsBbBsSsSbBsSsBsSbSbSbSsSsSbSbSbSsSsSbBsSsSsBsSsSsSsBbBsSbSsSbSbSsSsSbBsSsBsSsSsSsBbBsSbBsSsBsSsSsSsSsBbBsBbSsBsSsSsSbSsSbSbSsSbBsSsSsBsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbBsSsBsSsSbBsSsSsBsSbSsSsBsBsSsSsSsBbBsSbSbSbSsSsSsBbSsBsSsSsSsSsBbBsSbSsSbSbSsSsSsSsBbBsBsSsSsSbBsSbSsSbSbSsBsSsSbBsSsSsSsSsBbBsSsBsBsSbSsSbSbSbSsSsSsSsSsBbBsBsSsSsBbSsSbSsBsBsSsSsBsBsSbSsSsSsSsBbBsSsBsBsSbSsBsSsBsSbSsSbSsBsBsSsSsSsSsBbBsBbSsSsBsSsSbSsBsBsSsSbBsSsSsBsSsBsSbSsBsSbSsBsBsSsSsSbSbSbSsSbSsBsBsSsBsBsSbSsSsSbBsSsBsSsSsBbBsSsSsBbSsSsBsSsSsSsSsBbBsSsBbBsSsSsSbBsSsSsBsBsSsSsBbSsSsBbBsSsSsSbSsSbSbSsSsSsBbSsBsSsBsSbSsBsSbSsBsBsSsSsBsSbSsBsSsBsSsSbB':
        return"I'LL STEAL THE HORSES AS SOON AS I CAN THINK OF A WAY TO GET THE MENDELEVIUM UNGUARDED."
    if sentence == 'BsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsSbSbSbSsSsSbBsBsSsSbSsBsBsSsBsSsSbSsBsSsBsSbBsSsSsBsBsSbSsSsBsBsSbSsBsBbSsSsSsSsBbBsSsSsSsBsSsBbSsBsSsSsBbSsSsBbBsSsSsSsSbBsBsSsBsBbSsSsSsSbSsBsBsSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsBbSsSsSsBsBsBbSsSsSsSsBsSbBsSsSsBsSbSsBsBsBbSsSsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsSsSsBbBsBsSbSsBsSsBsBsSsSbSsBsSsSbSsBsBsSsSsBbSsSsBbBsSsSsBbBsSsSsSsBsBsSbSsSsSsBsSsBbSsSsSsSbBsBsBsBsSsSbSsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSbBsBsSsSsSsSsSbBsBsSsSbBsBsSsSsBsSsBbSsSsSsBsBbSsBsBbSsSsSsBsSsSbSsBsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsBsSsSsBbSsSbBsSsBsSsBsBbSsSsSsSsBsSsBbSsSsBsSbBsSsSsSbBsBsSsSsBbBsSsSsSsBsBsSbSsBsSbSsBsSsSsBbBsSsSsBsSsSsBbSsSsBsSsBbSsBsSsSsBbSsBsSbSsBsSsSsBsSsBbSsSsSsSsBbBsBsBbSsSsSsBsSbSsSsBsSsSbBsBsSsBsBsSsSbSsSbBsSsSsBsBbSsBsSsS':
        return'THE KIDNAPPER TRIED TO LEAVE THE COUNTRY, BUT THE THE FBI WENT TO THE AIRPORT TO CESIUM.'
    if sentence == 'SbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsSsBsSbBsBsSsSbSsBsBbSsSsSsBsSsBsBbSsSsSbSbSbSsSsBsBsSsSbSsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsBsSsSsBbSsSsBsSsSbBsBsSsBsSbSsBsSsBsSbSsSsBsSsSbBsBsSbSsSsBsSbSsBsSsBsSsBbBsSsSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsBsSsBsSbSsSsSbBsSsBsSbSbSbSsSsSbBsSsSsBsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsBsSsSsSbBsSsBsSsSbBsBsBsSsSbSsBsBsSsSbSsSsSbBsSsBsSsBsSbBsSsSsSbSbSbSsSbSbSbSsSsBsSbSsSsBsSsBsSbBsSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsBsSbBsSsSsBbSsSsBsSsBbSsSsBsBsSsSsSbBsBsSsBsSbSsSsSbSbSbSsSbSbSbSsSsBsSsSsSbBsSsSbBsSsBsSsSbSbSbSsSsBsSbBsSsSsSbBsSsBsBsSbSsSsBsSbBsSsSsBsSsSbBsSsBsSsBsSbBsSsSbSsSbSbSsSbSsSbSbSsSbSsSbSbSsSsBsBsSbSsSsSsBsSbBsSsSbBsSsBsBsSsSsSbBsSsSbBsSsBsBsSbSsBsSsBsSsBsSbSsSsSbSbSbSsSbBsSsSsBsSsSsBsSbBsSsSbBsSsBsSsSbSbSbSsSsBsBbSsSsSbSbSbSsSsBsSsSsSbBsBbSsSsSsBsSsBbSsSsBsBsSbSsSsBsSbSbSsSbS':
        return"THE HUBCAPS ARE MISSING, THE SEATS ARE RIPPED AND THE DOORS ARE DENTED...WHERE'S THE CARBON?"
    else:
        return'MANY PEOPLE WANT TO BE COWBOYS. THEY WANT TERBIUM SO THEY CAN LEARN HOW TO HERD CATTLE AND HOW EUROPIUM.'